### ISSUE TITLE
Show message-only coachmarks

### ISSUE THREAD

**Issue by kaandedeoglu** [ephread/Instructions#1]
Sometimes it is preferable to display just a text, without a next button or a separator. It seems `Instructions` does not support this at the moment. But I think it would be a good addition.

**Comment by kaandedeoglu** [comment]
fair enough :) I'd like to send a pull request for this if you're not completely against the idea.

**Comment by ephread** [comment]
I'm not completely against the idea. ;) How do you envision this? Another `CoachMarkBodyDefaultView`-like class with only text in it?

Do you think the “default” views are really usable “as-is”? I actually never thought anyone would use the “default” styles!

**Comment by kaandedeoglu** [comment]
Yes why not, most people just want basic views as long as they are somewhat configurable.

Things would get a lot more flexible if the `hintText` and `nextText` were given in the constructor. like 

```swift
coachMarksController.defaultCoachViewsWithArrow(true, arrowOrientation: coachMark.arrowOrientation, hintText: String, nextText: String?)
```
and the `separatorView` and the `nextLabel` were added iff `nextText` is non-nil.

Of course, thinking about it now, it all takes 1 subclass similar to the `CoachMarkBodyDefaultView` per project. So what you did is totally valid as well :)

**Comment by ephread** [comment]
I guess giving a little more flexibility to the “default” coach mark is okay. :) Go for it!

**Comment by ephread** [comment]
@kaandedeoglu any updates on that pull request? :)

**Comment by kaandedeoglu** [comment]
@ephread sorry have been super busy - I've already implemented something similar for my own use case, but it's not generic enough yet. Will update you on it when I get a chance. I can close this for the time being if your prefer.

**Comment by ephread** [comment]
Alright, we're all busy, aren't we :). That's no big deal, the issue can remain open, we'll close it once the pull request is ready. I simply wanted to make sure the feature was still in the pipeline!

**Comment by estebansotoara** [comment]
Hi
I saw this issue open and decided to give a hand, I added the constructor
```defaultCoachViewsWithArrow(withArrow: Bool = true, arrowOrientation: CoachMarkArrowOrientation? = .Top, hintText: String, nextText: String?)```
as kaandedeoglu suggested and follow the same rule, only shows the ```nextLabel``` and ```separatorView``` if ```nextText``` is provided.

I leave the original
```defaultCoachViewsWithArrow(withArrow: Bool = true, arrowOrientation: CoachMarkArrowOrientation? = .Top)```
in case anyone want or need to set the hintText and nextText later (also for retrocompatibility)

@ephread I have a fork with the changes (https://github.com/estebansotoara/Instructions/tree/ShowMessageOnlyCoachmarks), you can check it out and if you like it I can make a PR

**Comment by ephread** [comment]
Thanks @estebansotoara! I'll take a look in the next few days. ;)

**Comment by ephread** [comment]
@estebansotoara sorry for the HUGE delay, it looks mostly good ;), can you start a PR, so I can make few suggestions on the related issue?

**Comment by estebansotoara** [comment]
Done, the PR is #18

**Comment by hardikdevios** [comment]
please merge this PR and update the podspec

**Comment by ephread** [comment]
PR #18 was merged.
