### ISSUE TITLE
 Working perfectly in iOS 9 but Screen goes black in iOS 8

### ISSUE THREAD

**Issue by hammyhamza** [ephread/Instructions#10]

**Comment by ephread** [comment]
Thank you for reporting this bug.

Can you provide more details about the issue?

- On which subversion of iOS 8 do you encounter the bug? (8.1, 8.2… 8.4)
- Which device?
- What are the steps I should follow to reproduce the issue?

**Comment by hammyhamza** [comment]
Sorry for not testing it properly its working perfectly the problem was on my side.
Thanks for this wonderful library
