### ISSUE TITLE
Could be possible to change OverlayView delegate?

### ISSUE THREAD

**Issue by LiborZ** [ephread/Instructions#100]
Hi,
would it be possible to make delegate in OverlayView public (and OverlayViewDelegate protocol)? I want to have options to change what happened when user clicked on overlay. For example I don't want to skip just one step but skip all steps and hide instructions. I made it by these modifications but it's just local and when I need update libraries there would be problem. So what it be possible someway? Maybe delegate can stay internal but you can add method to change delegate or something like that. Thanks

**Comment by ephread** [comment]
Hello @LiborZ, if I understand correctly your needs, you can use `showNext(numberOfCoachMarksToSkip numberToSkip: Int = 0)` on `CoachMarkController.flow` to skip certain coach marks, or `CoachMarksController.stop()` to complete the flow.

Touching the overlay will eventually trigger `func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkWillLoadAt index: Int) -> Bool` for the next coach mark in the queue. There, based on the index, you can choose to skip all remaining coach marks.

**Comment by LiborZ** [comment]
I want to skip all marks but only if user touch the overlay. Yes overlay will eventually trigger `func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkWillLoadAt index: Int) -> Bool` but it's trigger even if I touch coach mark before. I need to detect if user touch overlay or touch coach mark.

**Comment by ephread** [comment]
Alright, thanks for the clarification. We can definitely split the two! I'll put that on the roadmap.

**Comment by LiborZ** [comment]
Are you planning new version with this enhancement any time soon? :) Thanks for info

**Comment by LiborZ** [comment]
Any progress with this? This should be change only in 3 lines of code :) Just change delegate properties from internal to public :)

**Comment by ephread** [comment]
1.1.0 introduces a new delegate method which should suit your needs, see [here](https://github.com/ephread/Instructions#react-when-the-user-tap-the-overlay) 😉
