### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by zzdjk6** [ephread/Instructions#101]
I have monitored a crash from end user, but I can't reproduce it, the logs below:

0 Instructions	_TFC12Instructions11FlowManager22createAndShowCoachMarkfTSb_T_ (FlowManager.swift:184)
 (FlowManager.swift:184)
1 Instructions	_TFC12Instructions11FlowManagerg10dataSourceXwGSqPS_35CoachMarksControllerProxyDataSource__ (FlowManager.swift:0)
 (FlowManager.swift:0)
2 Instructions	__TFFC12Instructions11FlowManager9startFlowFT22withNumberOfCoachMarksSi_T_U_FT_T_ (FlowManager.swift:87)
 (FlowManager.swift:87)
3 Instructions	__TPA__TTRXFdCb__dT__XFo__dT__ (CoachMarksViewController.swift:0)
 (CoachMarksViewController.swift:0)
4 Instructions	__TFFC12Instructions24CoachMarksViewController23prepareToShowCoachMarksFFT_T_T_U0_FSbT_ (CoachMarksViewController.swift:147)
 (CoachMarksViewController.swift:147)
5 UIKit	-[UIViewAnimationBlockDelegate _didEndBlockAnimation:finished:context:] + 492
6 UIKit	-[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 312
7 UIKit	-[UIViewAnimationState animationDidStop:finished:] + 160
8 QuartzCore	CA::Layer::run_animation_callbacks(void*) + 260
9 libdispatch.dylib	__dispatch_client_callout + 16
10 libdispatch.dylib	_dispatch_main_queue_callback_4CF + 1000
11 CoreFoundation	___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
12 CoreFoundation	___CFRunLoopRun + 1660
13 CoreFoundation	CFRunLoopRunSpecific + 444
14 GraphicsServices	GSEventRunModal + 180
15 UIKit	-[UIApplication _run] + 684
16 UIKit	UIApplicationMain + 208
17 Misehome	main (main.m:14)
18 libdyld.dylib	_start + 4

--------

I think we should not use any `Force-Unwrap` in code, it's not safe.

**Comment by ephread** [comment]
Hey @zzdjk6, thanks for reporting the issue. I'll look into it.

Force unwraping variable can make sense, such as making unrecoverable errors explicit. 😉

**Comment by ephread** [comment]
I was never able to reproduce this crash. I am going to close it for now. Feel free to re-open if it occurs again.
