### ISSUE TITLE
Update podspec

### ISSUE THREAD

**Issue by jlaws** [ephread/Instructions#102]
The podspec is out of date, can you update it to match what is on master?

**Comment by ephread** [comment]
@jlaws, sorry for the lack of update. The next version fixing the blur and supporting Swift 3 will be released around the end of this month. Thanks for your patience!

**Comment by ephread** [comment]
Instructions 1.0.0-beta.1 was just released (🎉), thanks for your patience and sorry for the delay.

**Comment by jlaws** [comment]
You still need to publish the updated podspec to the cocoapods trunk.  Calling pod update still gives the 0.5 version

**Comment by ephread** [comment]
The pod was published to the trunk this morning, few minutes before I closed the issue. I guess a problem occurred (or perhaps they ignore `-beta` versions on purpose, I'm not too familiar with CocoaPods).

http://cocoapods.org/pods/Instructions shows the right version at the top, but nothing else was updated. I'll investigate.

**Comment by ephread** [comment]
Seems they were properly added to the spec.

https://github.com/CocoaPods/Specs/tree/c2591f6ca694064dcfaddb2c8ed3d199ab379e25/Specs/4/9/c/Instructions
https://github.com/CocoaPods/Specs/tree/7647a29643e56045bdcdb2da171e20eab40450f3/Specs/9/8/3/InstructionsAppExtensions

That's awkward.

**Comment by ephread** [comment]
Specifying the exact version in the Podfile works.

```ruby
pod 'Instructions', '1.0.0-beta.1'
```

I didn't know CocoaPods would “hide” the beta versions, but come to think of it, that makes sense. I'll update the README.
