### ISSUE TITLE
Suggested Update to ReadMe Installation Instructions

### ISSUE THREAD

**Issue by jessgates** [ephread/Instructions#103]
Hello, love the repository, I have a small suggestions to the ReadMe under the Installation instructions include the following.

If Installing to use with Swift 3:
pod 'Instructions', :git => 'https://github.com/ephread/Instructions.git'

Thanks!

**Comment by ephread** [comment]
You're right @jessgates, the following part of the README seems to be quite confusing.
> Xcode 8 / Swift 3 (use `master`)

A proper version will normally be published by the end of the month, I've had some issues with the blur support on iOS 10, but it's mostly solved by now. If it's delayed again, I'll update the README !

**Comment by ephread** [comment]
Obsoleted by the release of version 1.0.0-beta.1.
