### ISSUE TITLE
can't compile on Swift 3

### ISSUE THREAD

**Issue by galblank** [ephread/Instructions#104]
keeps complaining about tons of issues :(

**Comment by sambing** [comment]
Remove **pod 'Instructions', '~> 0.5**' from your podfile and add :
pod 'Instructions', :git => 'https://github.com/ephread/Instructions'
install the pod again

**Comment by Salmancs43** [comment]
Hi I installed pod 'Instructions' but it keep containing tons of issues.

**Comment by ephread** [comment]
Thanks for the answer @sambing. Closing.
