### ISSUE TITLE
Not working on swift 3.0

### ISSUE THREAD

**Issue by Salmancs43** [ephread/Instructions#106]
Hi when i  installed the pod for swift 3.0 it gives tons of issues and 10 to 15 issues compiler didn't know. :(

**Comment by ephread** [comment]
Hello @Salmancs43, the master branch holds the swift 3-compatible version.
You can use the following line:

```ruby
pod 'Instructions', git: 'https://github.com/ephread/Instructions.git', branch: 'master'
```
