### ISSUE TITLE
App freezes while running

### ISSUE THREAD

**Issue by psubhashish** [ephread/Instructions#108]
![img_1891](https://cloud.githubusercontent.com/assets/1258090/25655932/76b0da62-3014-11e7-9781-c423fbe7d2de.PNG)
The app just froze like the above and I could not do anything but shut it down forcefully.

**Comment by ephread** [comment]
Hello @psubhashish, is it caused by Instructions? I can't seem to identified anything related to Instructions on your screenshot, could you provide me with a bit more details?

**Comment by psubhashish** [comment]
I'm not sure actually. I was trying to record and it just froze. I tried to restart the app and there was no progress.

**Comment by ephread** [comment]
I'm closing, as it doesn't seem to be caused by Instructions. If you've got more details on the issue, feel free to re-open.
