### ISSUE TITLE
Issue in Swift 3

### ISSUE THREAD

**Issue by tiwariammit** [ephread/Instructions#109]
After installing Instructions pod in xcode 8, it shows the lots of issue.

**Comment by Salmancs43** [comment]
pod 'Instructions', :git => 'https://github.com/ephread/Instructions.git'
Install this pod.

**Comment by waleedAlmubarak** [comment]
Awesome!

**Comment by ephread** [comment]
That's a dup of a dup, clear answer, I'm closing. ;)
