### ISSUE TITLE
Change the position of coach mark controller

### ISSUE THREAD

**Issue by Salmancs43** [ephread/Instructions#111]
Hi How can we change the coach mark view. For example when keyboard appears textfield move ups but the coach mark remain at the same position? Is there anyway to do  this? Thanks

**Comment by ephread** [comment]
Hey @Salmancs43, that's an oversight on my part. I'll think of something to deal with this case.

**Comment by ephread** [comment]
It's partially fixed on `master`, I'll update the README soon with how a “clean” transition can be achieved.

**Comment by vgvishesh23113** [comment]
i am trying to add multiple coach marks but the frame displayed is only the last one?
i will post a link to my question on stackoverflow . Could anyone provide some insights ? Maybe I am doing something wrong? 
https://stackoverflow.com/questions/54290193/ios-swift-coach-marks-walk-through-instructions-misbehaving?noredirect=1#comment95403457_54290193

**Comment by vgvishesh23113** [comment]
and is it possible to add coach marks on an action, for example i want user to tap on a button and then add a coach mark on the new view? or something along those lines?

**Comment by ephread** [comment]
@vgvishesh23113 please open a brand new issue for the problem you're having, I'll try to help you there.

**Comment by vgvishesh23113** [comment]
ok

**Comment by dharmendra-ios** [comment]
Hi @ephread, Could you please tell me how to move up coach mark view when keyboard appear on textField.

**Comment by ephread** [comment]
@dharmendra-ios, it's probably easier to pause the flow and hide the Coach Mark, wait for the keyboard animation to complete and restore/show the same coachmark again. You can take a look at [this example](https://github.com/ephread/Instructions/blob/master/Examples/Example/Sources/Core/View%20Controllers/Delegate%20Examples/KeyboardViewController.swift), or [that example](https://github.com/ephread/Instructions/blob/master/Examples/Example/Sources/Core/View%20Controllers/Delegate%20Examples/PausingCodeViewController.swift).

**Comment by ephread** [comment]
I tried to make this work automatically few months ago.

I don't think it's going to be possible, because keyboard notifications are also triggered before/after size transitions. There's no way to know for sure whether the keyboard was dismissed because of the size transition or as a result of another action. This means it's impossible to support this in a generic way and therefore it needs to be handled manually on a case by case basis.

Sorry :/
