### ISSUE TITLE
Question: create a more flat look to the coachmark

### ISSUE THREAD

**Issue by oferRounds** [ephread/Instructions#112]
Hi @ephread and all

First, @ephread — thanks again for this really awesome library! (already wrote you in the past).

I’m trying achieve a more flat look to the coachmark: remove the 3D illusion, and just add a minor shadow instead.

I was trying to look on the image assets which are currently used, in order to instruct my designer friend to  create one which will achieve this effect, but was not sure how to instruct him.

Any thoughts about can this be achieved? Does anyone have such assesses?

Thanks!
Ofer

**Comment by ephread** [comment]
You're welcome again @oferRounds ;)

To change the background, you'll need to provide your own, customized views. You can take a look at the [default views] or [the custom views of the example], copy them and tweak them to fit your needs.

The background of the coach marks are simply defined by two resizable images. One will be used to display the coach mark in its “idle” state, while the other will be used to display highlights.

![screen shot 2017-05-18 at 17 14 21](https://cloud.githubusercontent.com/assets/722366/26210499/08140e66-3bf0-11e7-9086-6a0f6cc9adc9.png)

If you're using arrows, you'll need to provide assets for both the “top” arrow and the “bottom” arrow, used depending on the orientation. Arrow also have [two states], “idle” and “highlighted”.

The tricky part is when Instructions will merge the arrow with the body of the coach mark. You'll need to slice the assets properly to make it feel seamless. For instance, the border doesn't run around the entire arrow. Rather, it's shifted, to let the body of the arrow overlap the shadow of the coach mark.  If you want to make the minor shadow run around the entire coach mark, you'll probably need to use a similar technique to make it look seamless

![screen shot 2017-05-18 at 17 42 25](https://cloud.githubusercontent.com/assets/722366/26210993/a06964da-3bf1-11e7-99a8-13d1a8523746.png)

Also remember that you can adjust the vertical gap between the arrow and the body using `CoachMark.gapBetweenBodyAndArrow` (if I recall correctly, the more negative, the further away). The default value is `2.0`.

[default views]:
 https://github.com/ephread/Instructions/tree/master/Sources/Extra/Default%20Views
[the custom views of the example]: https://github.com/ephread/Instructions/tree/master/Examples/Example
[two states]: https://github.com/ephread/Instructions/tree/master/Sources/Supporting%20Files/Images.xcassets

**Comment by oferRounds** [comment]
@ephread — thanks so much for this detailed explanation! I’ll try it :)

**Comment by ephread** [comment]
I'm closing the issue, feel free to re-open if you need more informations.

**Comment by oferRounds** [comment]
Thanks! 👍
