### ISSUE TITLE
Fail to build using Carthage

### ISSUE THREAD

**Issue by trialabc** [ephread/Instructions#115]
I am using Carthage and wanna download this. However, it give error saying "Task failed with exit code 65". Is there a problem with the build or my setting?

**Comment by sjackk** [comment]
Same error. In carthage log file I found:

=== CLEAN TARGET InstructionsAppExtensions OF PROJECT Instructions WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
warning: no umbrella header found for target 'InstructionsAppExtensions', module map will not be generated

=== BUILD TARGET InstructionsAppExtensions OF PROJECT Instructions WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
warning: no umbrella header found for target 'InstructionsAppExtensions', module map will not be generated

Please fix it

**Comment by ephread** [comment]
Hey @trialabc, sorry for the lack of reactivity. It's normally fixed by #107, try with `master`.
