### ISSUE TITLE
Minimum iOS version higher then in v0.5.0

### ISSUE THREAD

**Issue by wbervoets** [ephread/Instructions#116]
Hello,

Can you please put the mimimum version of iOS on 8.0 in the new 1.0 beta?

Thanks
Wim

**Comment by ephread** [comment]
Hey @wbervoets, I dropped the iOS 8 support for 1.0.0. I can sneak '8.0' back in as the minimum version, but I won't provide fixes for iOS 8 if things go awry. I'll gladly accept external pull requests, though. ;)

I'll revert the change in 1.0.0-beta.2.

**Comment by derick182** [comment]
Hi, same issue here.
Cannot install version 1

**Comment by ephread** [comment]
[`swift3`](https://github.com/ephread/Instructions/tree/swift3) now provides a last version targeting iOS 8+ and Swift 3.2
