### ISSUE TITLE
Animation question - Animate the transparency of the overlay

### ISSUE THREAD

**Issue by ergunkocak** [ephread/Instructions#117]
Hello,

First of all thanks for such useful library 👍 

Is it possible to animate background transparent layer as in : 

https://raw.githubusercontent.com/wooplr/Spotlight/master/art/intro.gif?token=AA5ZAHdvAspW6Zj8YyyKamkV7jWXFtMHks5XaQovwA%3D%3D

Best Regards

**Comment by ephread** [comment]
Thanks @ergunkocak, you're welcome!

Sadly, not yet. Custom animations of the overlay and the coach marks are not supported, but it's on the roadmap.

**Comment by jlubeck** [comment]
Hi! What about just a simple Fade animation for the overlay? Currently it just appears. I saw the animation delegates for the coachmarks themselves, but not for the overlay

Thanks!

**Comment by ephread** [comment]
@jlubeck the overlay should fade in as it appears. If it just appears, then something went wrong somewhere.

**Comment by jlubeck** [comment]
@ephread that's strange. I'm just doing a standard setup

```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated);
            self.coachMarksController.overlay.color = UIColor.black.withAlphaComponent(0.2)
            self.coachMarksController.dataSource = self
            self.coachMarksController.delegate = self
            self.coachMarksController.start(in: .window(over: self))
    }
```

I'm on the simulator though, hanve't tried on physical device yet. Could that be why?
