### ISSUE TITLE
How to change skip view position

### ISSUE THREAD

**Issue by dmitrysimkin** [ephread/Instructions#118]
Hi, I didn't found public API how to change the skip view location. I see internal code to be default in top right corner. But for me I need it in top left corner. How can I achieve it?
Thanks in advance.

**Comment by ephread** [comment]
Hello @dmitrysimkin, you can use the following `CoachMarksControllerDataSource` method, as [specified in the README](https://github.com/ephread/Instructions#datasource) (the snippet seems outdated, I'll update it).

```swift
func coachMarksController(_ coachMarksController: CoachMarksController, constraintsForSkipView skipView: UIView, inParent parentView: UIView) -> [NSLayoutConstraint]?
```

You can also take a look at [this Example](https://github.com/ephread/Instructions/blob/master/Examples/Example/CustomViewController.swift#L156).

**Comment by dmitrysimkin** [comment]
Thank for quick answer! 

Sorry, I've missed this part, thanks for pointing me out.

**Comment by ephread** [comment]
You're welcome ;)
