### ISSUE TITLE
Coach mark without linked view

### ISSUE THREAD

**Issue by dmitrysimkin** [ephread/Instructions#119]
Is there any way to show coach mark without relation to any view? Please consider following example, I want to start walkthrough from generic welcome message and place it in center, there is no yet view to cutout.
Thanks

**Comment by ephread** [comment]
It's not really supported, but [#83](https://github.com/ephread/Instructions/issues/83#issuecomment-261511352) details a possible workaround.

**Comment by dmitrysimkin** [comment]
Thanks, that helps!

PS. Awesome framework 👍
