### ISSUE TITLE
Uploads to iTunes Connect fail when framework's Info.plist versions do not conform to %d.%d.%d format

### ISSUE THREAD

**Issue by dmitrysimkin** [ephread/Instructions#120]
Hi, 
I've encountered with en error uploading my app integrated with 'Instructions' framework to the store. That's because Instructions.framework has '1.0.0-beta.1' version number.  Please see screenshot. 
<img width="583" alt="screen shot 2017-06-09 at 5 48 36 pm" src="https://user-images.githubusercontent.com/7154376/26981378-9703612c-4d3d-11e7-963a-0c41725dfeb8.png">

I work with XCode 8.3.2

Thanks for help

**Comment by ephread** [comment]
Sorry about that @dmitrysimkin. Oversight on my end.
I assume you're using Carthage. Once in the project directory, you can use the following commands to change the version strings:

```bash
$ defaults write $PWD/Carthage/Build/iOS/Instructions.framework/Info.plist CFBundleShortVersionString 1.0.0
$ defaults write $PWD/Carthage/Build/iOS/InstructionsAppExtensions.framework/Info.plist CFBundleShortVersionString 1.0.0
```

The beta phase will be very quick.

**Comment by dmitrysimkin** [comment]
Thanks!
