### ISSUE TITLE
Can you lower the deployment target?

### ISSUE THREAD

**Issue by Sweeper777** [ephread/Instructions#121]
I want to support iOS 8. Are you using anything that's not available in iOS? If that is not the case, can you lower the deployment target to iOS 8?

**Comment by ephread** [comment]
Hello @Sweeper777, please see #116. I'm actually using the iOS 9+ syntax for autolayout, but I'll make a last iOS 8-compatible version using the legacy syntax. Please note, however, that I won't be supporting iOS 8 anymore after that. Pull request will be welcome, tough.

**Comment by Sweeper777** [comment]
Thank you!

**Comment by ephread** [comment]
[`swift3`](https://github.com/ephread/Instructions/tree/swift3) now provides a last version targeting iOS 8+ and Swift 3.2
