### ISSUE TITLE
please make the availablty of used pod in example 

### ISSUE THREAD

**Issue by vuppalasivakumar** [ephread/Instructions#125]
It is one of the worst library what i had seen beacuse pod will not install for pod 'Instructions', '1.0.0-beta.1'
and how ever i installed pod but methods are different  in example and installed pod then what is the use of example, please make sure the availablity of the used pod in example.

**Comment by ephread** [comment]
You know, no one forces you to use it if it's the worst library you've ever seen. 🙃

**Comment by vuppalasivakumar** [comment]
I am saying that to make the pod available for given pod link other than that nothing is there bro. But ur Example one is working fine and having good effects.

**Comment by Ferannor** [comment]
@vuppalasivakumar Man you can update the README if the problem is only that case. That what is f... magical with Github!

**Comment by ephread** [comment]
Whatever the issue was exactly, it's probably solved by `1.0.0`.
