### ISSUE TITLE
Is it possible to continue the flow of the coach mark after presenting new viewcontroller

### ISSUE THREAD

**Issue by Nathan2017** [ephread/Instructions#126]
I am trying to continue the flow of a coach mark in one viewcontroller to other viewcontroller after presenting the viewcontroller, but some how it doesnt continue the flow, but i still see the skip button.

**Comment by ephread** [comment]
Hello @Nathan2017, sadly cross-controller walkthrough is currently not supported 😕. You'll have to stop the flow, change the controller, and start it again on the new controller.

**Comment by Nathan2017** [comment]
Oh ok thanks for the reply, its a great library anyway
