### ISSUE TITLE
Lock orientation?

### ISSUE THREAD

**Issue by rtnlsltn** [ephread/Instructions#132]
I'm using some viewcontrollers in my project that are using a rotation lock via the navigation controller. Using these methods on the Instructions VC's don't appear to work (shouldAutorotate false, supportedInterfaceOrientations .portrait). I'm curious if there's a way I can lock orientation so the instructions don't rotate when the device does?

**Comment by ephread** [comment]
Should be solved by 1.1.0. On start, Instructions will now retrieve `shouldAutorotate` and `supportedInterfaceOrientations` from the controller.
