### ISSUE TITLE
Pause -> remove layer -> resume

### ISSUE THREAD

**Issue by Jasperav** [ephread/Instructions#134]
I want to pause my flow, for example at index 1. When it hits index 1, the white layer should be removed from the screen and the coachMarks. The instructions should pause and it should look like it is removed.
 I thought implementing this function would work:

    func coachMarksController(_ coachMarksController: CoachMarksController, willShow coachMark: inout CoachMark, at index: Int) {
        switch index {
        case 1:
            coachMarksController.flow.pause()
        default:
            break
        }
    }

However the function never gets executed. I did set the delegate. Thanks.

**Comment by danparnella** [comment]
I've also noticed that "willShow" is no longer firing.  This did used to work when I was using the 0.5.0 release.

**Comment by danparnella** [comment]
Ok, just tracked down that the func name has changed to:
`func coachMarksController(_ coachMarksController: CoachMarksController, willShow coachMark: inout CoachMark, afterSizeTransition: Bool, at index: Int) {}`

This should be updated in the ReadMe

**Comment by Jasperav** [comment]
Hi @danparnella now that function is calling, thanks. 

However I am still unable to remove the overlay. Even if i set the overlay color to .clear, I can not get rid of it.

**Comment by ephread** [comment]
Thanks @danparnella, I thought I mentioned it in the README, I'll make an update.

@Jasperav, see #136, I'll batch-fix of your issue, his and #131 in the near future.

**Comment by ephread** [comment]
Landed in 1.2.0.
