### ISSUE TITLE
Disable overlay for user interaction and then resume coachmarks

### ISSUE THREAD

**Issue by magicmikek** [ephread/Instructions#136]
Is it possible to disable the overlay when I use `coachMarksController.flow.pause()` such that the user can perform some interaction ( two button clicks ) and then use `self.coachMarksController.helper.updateCurrentCoachMark()
                self.coachMarksController.flow.resume()`

to continue with the instructions?

**Comment by ephread** [comment]
Not yet, but there's a [PR](https://github.com/ephread/Instructions/pull/131) relating to this. So it'll be possible in the near future!

**Comment by ephread** [comment]
Landed in 1.2.0, see [Pausing and resuming the flow](https://github.com/ephread/Instructions#pausing-and-resuming-the-flow).
