### ISSUE TITLE
Suppor for UITabBar tabs 

### ISSUE THREAD

**Issue by dreed47** [ephread/Instructions#146]
Does Instructions have support for attaching coach marks to the tabs of a UITabBar?  The only way I can figure out how to do this it to add my own custom UIViews and try to position them over the tabs.  This approach is very troublesome when trying to account for the different screen resolutions.  Is there another way to do it or is it just not supported?

**Comment by ephread** [comment]
Hello @dreed47, unfortunately there won't be any direct support for `UIBarButtonItem` and subclasses, because they hold their views inside a private property. You've got two options:

1. Highlighting the entire Tab Bar, but placing the arrow above the element you wish to emphasize, by using the `CoachMark.pointOfInterest` property.

2. Access the private view property of the item you wish to highlight, as described in #87 and in #31.

**Comment by dreed47** [comment]
Thank for the tips.  I didn't think there was a way to highlight the entire tabbar?  Am I wrong?

**Comment by ephread** [comment]
Actually, `UITabBar` is a subclass of `UIView`, so you can pass the `tabBar` to Instructions' helpers to get the cutout path, or use its frame to create the cutout path manually.

**Comment by dreed47** [comment]
very cool!  thx

**Comment by mgurnani** [comment]
@ephread - When you say _"Highlighting the entire Tab Bar, but placing the arrow above the element you wish to emphasize, by using the CoachMark.pointOfInterest property."_
Can you guide how to do that please - positioning the arrow over correct element?

**Comment by ephread** [comment]
@mgurnani The [_mixed_ example](https://github.com/ephread/Instructions/blob/master/Examples/Example/Source/Core/View%20Controllers/CustomViewController.swift#L79) shows a possible solution. You just have to set the `pointOfInterest` to a custom position.

I'm going to close the issue for now.

**Comment by arishanapalli** [comment]
```
                guard let view = self.tabBarController?.tabBar.items?[1].value(forKey: "view") as? UIView else
                {
                    return coachMarksController.helper.makeCoachMark()
                }
                return coachMarksController.helper.makeCoachMark(for: view)

```

Try Above Code for selected TabBar Item you can have coachMark for it.
