### ISSUE TITLE
iOS 11.2.2 flickering UI markers/highlight

### ISSUE THREAD

**Issue by VanHoutte1337** [ephread/Instructions#150]
Hello

Since I installed 11.2.2 on my iPhone X I noticed there is an issue when showing the markers. Before showing the marker, the UI element is highlighted, a brief moment after that the highlight is gone and briefly after that, the marker plus the highlight is shown which causes a fast flickering on the UI.

You can test this when running the example app on iOS 11.2.2.

[Proof on YouTube](https://www.youtube.com/watch?v=56Bu_9LUf6I&feature=youtu.be)
If you set display speed to 0.25 you will see what I mean.

Thanks in advance!

**Comment by ephread** [comment]
Ouch. This doesn't look nice at all. Thanks for reporting the issue @VanHoutte1337. I'll take a look.

**Comment by ephread** [comment]
@VanHoutte1337 I haven't been able to witness the issue, does it still happen as of 11.2.6 ?

**Comment by VanHoutte1337** [comment]
I haven't seen it anymore since 11.2.6. I did check 11.2.5 and that version still gave me the bug.

**Comment by ephread** [comment]
Since we're now on 11.4, I believe we can consider that it was a slight bug on Apple's end. I'm going to close the issue, if you witness the problem again, don't hesitate to reopen the thread.
