### ISSUE TITLE
Add Ability to Change Font

### ISSUE THREAD

**Issue by AchintyaAshok** [ephread/Instructions#151]
Would it be possible to pass in the font for a coach? Also, formatting wise how feasible is it to change the type of paragraph alignment? Right now it's justified but would it be possible to be left or right aligned instead?

**Comment by ephread** [comment]
Hello @AchintyaAshok, I recommend you to provide custom view, with the font you wish to use. See [here](https://github.com/ephread/Instructions#providing-custom-views). You can also take a look at how the default views are [implemented](https://github.com/ephread/Instructions/tree/master/Sources/Instructions/Extra/Default%20Views).

The default views are not really meant to be customized. It's much more flexible for you to provide your custom views.

**Comment by AchintyaAshok** [comment]
Got it thanks @ephread

**Comment by JustinBobo** [comment]
Just wanted to add that you can edit the font by setting the attributedText property as opposed to the text property. Example:

let nextString = NSMutableAttributedString()
nextString.appendRegular("Next", size: 14)
coachViews.bodyView.nextLabel.attributedText = nextString

@discardableResult func appendRegular(_ text: String, size: CGFloat) -> NSMutableAttributedString {
        guard let latoRegular = UIFont(name: latoRegularFont, size: size) else { return NSMutableAttributedString() }
        let attributes = [NSAttributedStringKey.font: latoRegular]
        let normalString = NSMutableAttributedString(string: "\(text)", attributes: attributes)
        self.append(normalString)
        return self
    }

**Comment by hamidptb** [comment]
you can using from this in your coachMarkViewsAt index ... func :
`coachViews.bodyView.hintLabel.font = UIFont(name: "IRANSansMobile", size: 17)`
