### ISSUE TITLE
View Hierarchy Issue in TabBar Controller

### ISSUE THREAD

**Issue by RoshanJSequeira** [ephread/Instructions#156]
Hi,

When used to highlight UITabBarController tabs , The current elements highlighting rectangle is behind the tabbar item. 

Image attached

![simulator screen shot - iphone 8 plus - 2018-02-27 at 11 53 50](https://user-images.githubusercontent.com/28585409/36713830-75fa3ca2-1bb5-11e8-8f17-5a1b16b45845.png)

**Comment by o15a3d4l11s2** [comment]
Could you please share he code that you are using to highlight the exact tab bar item? Then I might be able to help you.

**Comment by ephread** [comment]
Thanks for your help @o15a3d4l11s2, since there hasn't been any update after your comment, I'm going to close the issue for now.
