### ISSUE TITLE
CoachMark is out of bounds if CoachMarkBodyView is created via a XIB.

### ISSUE THREAD

**Issue by schinj** [ephread/Instructions#169]
I am creating a Custom view for the the Body view using xib.

In delegate function `func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkViewsAt index: Int, madeFrom coachMark: CoachMark) -> (bodyView: CoachMarkBodyView, arrowView: CoachMarkArrowView?)`, I am creating the view from xib and returning that view in bodyView.

On running my application, I can see that the whole view is out of bounds.

Please let me know what's causing the issue. Thanks in advance.

**Comment by ephread** [comment]
Hey @schinj, thanks for reporting the issue.

Is Auto Layout breaking constraints? If so, could you paste the related console output here?

**Comment by schinj** [comment]
Hi @ephread 

Please find the console output below:
2018-05-30 00:39:42.660006+0530 [44631:754953] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000885550 UILayoutGuide:0x6000007a1b20'UIViewLayoutMarginsGuide'.trailing == Instructions.CoachMarkView:0x7fbae8e405f0.trailing NSSpace(0)   (active)>",
    "<NSLayoutConstraint:0x600000885640 H:[Instructions.CoachMarkView:0x7fbae8e405f0]-(0)-|   (active, names: '|':Instructions.InstructionsRootView:0x7fbae8c26c00 )>",
    "<NSLayoutConstraint:0x600000885460 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x6000007a1b20'UIViewLayoutMarginsGuide']-(16)-|(LTR)   (active, names: '|':Instructions.InstructionsRootView:0x7fbae8c26c00 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000885550 UILayoutGuide:0x6000007a1b20'UIViewLayoutMarginsGuide'.trailing == Instructions.CoachMarkView:0x7fbae8e405f0.trailing NSSpace(0)   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2018-05-30 00:39:42.663367+0530 [44631:754953] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000008852d0 Instructions.CoachMarkView:0x7fbae8e405f0.leading == UILayoutGuide:0x6000007a1b20'UIViewLayoutMarginsGuide'.leading NSSpace(0)   (active)>",
    "<NSLayoutConstraint:0x6000008855f0 Instructions.CoachMarkView:0x7fbae8e405f0.width <= 350   (active)>",
    "<NSLayoutConstraint:0x600000885640 H:[Instructions.CoachMarkView:0x7fbae8e405f0]-(0)-|   (active, names: '|':Instructions.InstructionsRootView:0x7fbae8c26c00 )>",
    "<NSLayoutConstraint:0x604000289ec0 'UIView-Encapsulated-Layout-Width' Instructions.InstructionsRootView:0x7fbae8c26c00.width == 375   (active)>",
    "<NSLayoutConstraint:0x6000008853c0 'UIView-leftMargin-guide-constraint' H:|-(16)-[UILayoutGuide:0x6000007a1b20'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':Instructions.InstructionsRootView:0x7fbae8c26c00 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x6000008852d0 Instructions.CoachMarkView:0x7fbae8e405f0.leading == UILayoutGuide:0x6000007a1b20'UIViewLayoutMarginsGuide'.leading NSSpace(0)   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2018-05-30 00:39:42.677048+0530 [44631:754953] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x604000495e50 h=-&- v=-&- OnboardingTipView:0x7fbae8d51c40.midX == Instructions.CoachMarkView:0x7fbae8e405f0.midX + 187.5   (active)>",
    "<NSLayoutConstraint:0x604000497d40 H:|-(0)-[OnboardingTipView:0x7fbae8d51c40]   (active, names: '|':Instructions.CoachMarkView:0x7fbae8e405f0 )>",
    "<NSLayoutConstraint:0x604000497d90 OnboardingTipView:0x7fbae8d51c40.trailing == Instructions.CoachMarkView:0x7fbae8e405f0.trailing   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x604000497d90 OnboardingTipView:0x7fbae8d51c40.trailing == Instructions.CoachMarkView:0x7fbae8e405f0.trailing   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2018-05-30 00:39:42.708193+0530 [44631:754953] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x604000498920 h=-&- v=-&- OnboardingTipView:0x7fbae8d51c40.midY == Instructions.CoachMarkView:0x7fbae8e405f0.midY + 88   (active)>",
    "<NSLayoutConstraint:0x604000497e30 V:|-(0)-[OnboardingTipView:0x7fbae8d51c40]   (active, names: '|':Instructions.CoachMarkView:0x7fbae8e405f0 )>",
    "<NSLayoutConstraint:0x604000497e80 OnboardingTipView:0x7fbae8d51c40.bottom == Instructions.CoachMarkView:0x7fbae8e405f0.bottom   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x604000497e80 OnboardingTipView:0x7fbae8d51c40.bottom == Instructions.CoachMarkView:0x7fbae8e405f0.bottom   (active)>

**Comment by ephread** [comment]
Looks like you need to set `translatesAutoresizingMaskIntoConstraints = false` on the views instantiated from the XIBs.

**Comment by schinj** [comment]
Hi @ephread ,

Thanks for the suggestion. Now the view is visible, but I am having a margin on one side of the view. For the corresponding coachMark, I have set the horizontal margin to 0. 

I am getting this log on console:
2018-05-30 11:04:16.800 [4313:3201583] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x14f8cdd20 Instructions.InstructionsRootView:0x14f87aea0.trailingMargin == Instructions.CoachMarkView:0x14f967b00.trailing>",
    "<NSLayoutConstraint:0x14f8cf1a0 H:[Instructions.CoachMarkView:0x14f967b00]-(0)-|   (Names: '|':Instructions.InstructionsRootView:0x14f87aea0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x14f8cdd20 Instructions.InstructionsRootView:0x14f87aea0.trailingMargin == Instructions.CoachMarkView:0x14f967b00.trailing>

**Comment by ephread** [comment]
Could you provide me with a screenshot showing the issue?

**Comment by schinj** [comment]
Yeah sure. Please find the attached screenshot.
![img_0613](https://user-images.githubusercontent.com/7895596/40720194-91e3c7d2-6433-11e8-89b0-5aa4087ef25a.PNG)

White area on the left side of the tip is what I am talking about.

**Comment by projectevo** [comment]
Also having this issue on iPhone 7+, however on the iPhone X seems to be working fine:
![simulator screen shot - iphone 7 plus - 2018-06-16 at 11 27 09](https://user-images.githubusercontent.com/36873751/41501387-621a741a-7158-11e8-96f3-bb685882896a.png)

**Comment by ephread** [comment]
Hey @projectevo, I don't think it's related. It looks like a safe area issue, which version are you using?

**Comment by projectevo** [comment]
@ephread the latest version.
I was able to fix it by creating a dummy view with an alpha of 0 and userinteractionenabled set to false.

**Comment by ephread** [comment]
@projectevo would be able to give `master`'s `HEAD` a try? I made some changes to the way Safe Areas are handled a couple of weeks ago, but I haven't made the release yet.

**Comment by nstele** [comment]
@projectevo did you solve the issue with iphone 7+?

**Comment by ARamy23** [comment]
@ephread I'm also facing this problem on the iPhone 6S+ 
is there anything new regarding this issue?

**Comment by ephread** [comment]
@ARamy23 I've been unable to reproduce the issue; can you provide me with a simple project in which you're facing the problem?

**Comment by ARamy23** [comment]
@ephread thanks and sorry for the late reply
I managed to find the problem and solving it
the bodyView was out of place for me because the width i've given it was bigger than the UIScreen's bounds
which resulted in it to go out of bounds, once i made the width suitable for different screen sizes (using a simple math actually since i couldn't handle it with constraints) 
it appeared just fine 👍 

sadly I can't provide u the project i was working on, but I'll try to reproduce the bug on a dummy project and send it to u in the weekend 

this is what i did to make the width work

Screen Width: BodyView Width
375: 310
X: Y 

Y = 310 * X / (375) where X is UIScreen's width

**Comment by ephread** [comment]
I fixed a couple of problems which might have been related to this one. Since the issue has been inactive for a while, I'm gong to close it. Fee free to open a new issue if the problem arises again with the coming version (1.5.0).

**Comment by zhaoying8703** [comment]
I have got the same issue. 
The body views not place in the center. 
Please let me know for any helps.
![image](https://user-images.githubusercontent.com/62020805/89850849-af071400-dbbd-11ea-922e-3e9ab7e05ea3.png)
