### ISSUE TITLE
Enhancement: use Instructions from within Objective-C file

### ISSUE THREAD

**Issue by oferRounds** [ephread/Instructions#17]
Would be great if this support could be added!

**Comment by ephread** [comment]
Hey @oferRounds Please see https://github.com/ephread/Instructions/issues/12 ;)

Unless Apple makes some changes to the way _mix & match_ work, Instructions will never be bridged to Objective-C, because it uses pure Swift types. However, you can make it work with a bit of Swift glue.

**Comment by oferRounds** [comment]
Thanks @ephread!

I'm currently looking into it, just want to update that the Objective-C example currently crashes when launched. I'm getting this error:

dyld: Library not loaded: @rpath/Instructions.framework/Instructions
  Referenced from: /var/mobile/Containers/Bundle/Application/CE836E5A-8CBF-4B2E-A9B9-57C5ACAB42F8/Instructions Example Objective-C.app/Instructions Example Objective-C
  Reason: image not found

**Comment by oferRounds** [comment]
I'm not sure which image is it referring to...

**Comment by oferRounds** [comment]
Ok, tried it using your approach - works like charm :)
Thanks a lot again!

**Comment by ephread** [comment]
You're welcome. ;)

Thanks for reporting this issue, I forgot to link the _Instructions_ framework from the Objective-C project (meh :/), that's why it doesn't start, the dynamic library is missing. I'll fix it as soon as possible!

**Comment by ephread** [comment]
Pre-closing, as `objective-c` won't be merged into `master` in the near future.
