### ISSUE TITLE
Is didEndShowingBySkipping used for both end cases, by skip or last CoachMark?

### ISSUE THREAD

**Issue by Rovel** [ephread/Instructions#174]
I want to change a users defalults bool after the instructions are finished or skipped

does `didEndShowingBySkipping` work for both? just evaluating the bool `skipped` ?

**Comment by ephread** [comment]
Hi @Rovel, that's correct, it works for both, just the way you described.

**Comment by Rovel** [comment]
thanks @ephread I'm doing something like this, but I aint getting no print in my console with the following code, am I missing something? does it need something in the viewDidLoad?

```
    func coachMarksController(_ coachMarksController: CoachMarksController, didEndShowingBySkipping skipped: Bool) {
        if skipped {
            print("+++++++ Skip Pressed!!!!")
        } else {
            print("+++++++ Intructions ended!!!!")
        }    
    }
```

**Comment by ephread** [comment]
> am I missing something? does it need something in the viewDidLoad?

Other than setting the `delegate` property of `CoachMarkController` (and in your case, `skipview` as well, `skipView` as well), you don't need to anything else. Maybe you simply forgot to set the delegate, a careless mistake I've done a zillion time!

This example [file](https://github.com/ephread/Instructions/blob/master/Examples/Example/Sources/Core/View%20Controllers/Debug/TestFlowViewController.swift) prints something for most delegate calls. You can check out the corresponding item in the example app (_Protocol Testing_), see if it prints stuff in your environment and compare the example file with yours.

**Comment by Rovel** [comment]
fixed! you were right, I was missing the `self.coachMarksController.delegate = self` in the viewDidLoad
Thanks 👊
