### ISSUE TITLE
CoachMark is showing on Wrong Position When scrolled the tableView.

### ISSUE THREAD

**Issue by vermaanand** [ephread/Instructions#176]
I have added CoachMark on Multiple cell of tableView. hidden cell just scrolled on the top but the position of CoachMark showing on wrong cell.
Please help out. I'm not able to set right position of CoachMark on Scrolling TableView.

code is below:

```swift
func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkAt index: Int) -> CoachMark {

    var coachMark : CoachMark
    var acell: CompactQuizCell!
    var trustCell: TrustScoreCell!

    guard let vc = matchesScreen.first as? MatchesV2ViewController else  {
        fatalError()
    }
    
    if index == 2 {
        let indexPath = IndexPath(row: 0, section: 3)
        vc.tableView.scrollToRow(at: indexPath, at: .top, animated: true)
        let indexTrust = vc.sectionList.index(of: .trustScore)!
        trustCell = vc.tableView.cellForRow(at: IndexPath(row: 0, section: indexTrust)) as! TrustScoreCell
    }
    
    if index == 1 {
        let indexPath = IndexPath(row: 0, section: 1)
        vc.tableView.scrollToRow(at: indexPath, at: .top, animated: true)
        let indexComp = vc.sectionList.index(of: .quiz)!
        acell = vc.tableView.cellForRow(at: IndexPath(row: 0, section: indexComp)) as! CompactQuizCell
        acell.instructionView.translatesAutoresizingMaskIntoConstraints = false
    }

    if matchesScreen.count > 0 {
        switch index {
        case 0:
            coachMark = coachMarksController.helper.makeCoachMark(for: chatBadgeView)
            coachMark.arrowOrientation = .top
        case 1:
            coachMark = coachMarksController.helper.makeCoachMark(for: acell.instructionView)
            coachMark.arrowOrientation = .top
        case 2:
            coachMark = coachMarksController.helper.makeCoachMark(for: trustCell)
            coachMark.arrowOrientation = .bottom
        case 3:
            coachMark = coachMarksController.helper.makeCoachMark(for: sparkInstructionView)
            coachMark.arrowOrientation = .bottom
        default:
            return coachMarksController.helper.makeCoachMark()
        }
        return coachMark
    }
    return coachMarksController.helper.makeCoachMark()
}
```

**Comment by ephread** [comment]
Hi @vermaanand, I see one issue which may be the culprit.

The following call:

```swift
vc.tableView.scrollToRow(at: indexPath, at: .top, animated: true)
```

will not scroll the table immediately, hence, all the code following that line will actually execute before the scroll is complete.

You've got a couple of options, you can wrap the `scrollToRow` call is a `CATansaction` with a completion block or you can wrap the scroll in a `UIView.animate`. Finally you can also use the`scrollViewDidEndScrollingAnimation` method on `TableViewDelegate`. I've used that method successfully in one of my app.

Take a look at all the answers from this [SO thread](https://stackoverflow.com/questions/4356256/how-to-get-notified-when-scrolltorowatindexpath-finishes-animating) for possible implementations.

**Comment by vermaanand** [comment]
@ephread thanks but I'm not able to return coachMark inside the completion block.

**Comment by vermaanand** [comment]
issue resolved @ephread  thanks

**Comment by vermaanand** [comment]
Just Scroll TableView inside delegate.
    func coachMarksController(_ coachMarksController: CoachMarksController, willHide coachMark: CoachMark, at index: Int) {
}

**Comment by ephread** [comment]
Great!
