### ISSUE TITLE
Instructions needs to be updated for Swift 4.2 compatibility.

### ISSUE THREAD

**Issue by ethanwa** [ephread/Instructions#181]
Instructions needs to be updated for Swift 4.2 compatibility. I'm getting a request to convert to it in Xcode 10 GM and there are lots of changes it requests.

**Comment by Derekhie** [comment]
Waiting for the same update. Thanks

**Comment by ephread** [comment]
Hey @ethanwa and @Derekhie, Swift 4.2 support is available in the [`swift4`](https://github.com/ephread/Instructions/tree/swift4) branch, but it will likely not be merged into master before a while.

**Comment by Derekhie** [comment]
Thanks
