### ISSUE TITLE
Skip position change

### ISSUE THREAD

**Issue by mouli457** [ephread/Instructions#186]
How can I set skip option on bottom?

**Comment by ephread** [comment]
Hey @mouli457, I don't understand what you're trying to achieve.

**Comment by mouli457** [comment]
I am using  skip option to stop the instructions, by default skip is displaying at right top (above the right bar button item),so I want change the skip button position.

**Comment by ephread** [comment]
@mouli457 Alright, the answer is [here, in the README](https://github.com/ephread/Instructions#let-users-skip-the-tour). You need to implement:

```swift
func coachMarksController(_ coachMarksController: CoachMarksController, constraintsForSkipView skipView: UIView, inParent parentView: UIView) -> [NSLayoutConstraint]?
```

**Comment by mouli457** [comment]
can you please  tell me how to change constraints values to change skip position?

**Comment by ephread** [comment]
Everything you need to know is in the README section that I've linked. Quoting:

> This method will be called by the CoachMarksController before starting the tour and whenever there is a size change. It gives you the skip button and the view in which it will be positioned and expects an array of NSLayoutConstraints in return. These constraints will define how the skip button will be positioned in its parent. You should not add the constraints yourself, just return them.
>
> Returning nil will tell the CoachMarksController to use the defaults constraints, which will position the skip button at the top of the screen. Returning an empty array is discouraged, as it will most probably lead to an akward positioning.
>
> For more information about the skip mechanism, you can check the Example/ directory.
