### ISSUE TITLE
Ambiguous use of 'coachMarkForView(_:bezierPathBlock:)'

### ISSUE THREAD

**Issue by eeschimosu** [ephread/Instructions#19]
in the method:
```swift
func coachMarksController(coachMarksController: CoachMarksController, coachMarksForIndex index: Int)
    -> CoachMark {
      var coachMark : CoachMark
      switch index {
      case 0:
        coachMark = coachMarksController.coachMarkForView(self.collectionView)
      case 1:
        coachMark = coachMarksController.coachMarkForView(self.imageButton)
      default:
        break
      }
      coachMark.gapBetweenCoachMarkAndCutoutPath = 6.0
      return coachMark
  }
```
when I try to assign the point of interest (at *case 0*)
```swift 
 coachMark = coachMarksController.coachMarkForView(self.collectionView)
``` 
I get the error: *Ambiguous use of 'coachMarkForView(_:bezierPathBlock:)*
The *case 1* works fine.

**Comment by ephread** [comment]
Thanks for reporting the issue, I'll look into it as soon as possible!

**Comment by ephread** [comment]
@eeschimosu I can't reproduce the issue.

There are indeed two methods named `coachMarkForView`, both returning `CoachMark`, but I fail to see how Swift could find the call ambiguous. I've got few questions:

1. I assume the type of `self.collectionView` is either `UICollectionView?` or `UICollectionView`, would it happen to be something else?
2. How did you import the library? By hand? with CocoaPods? with Carthage? Is it possible that you linked the library twice?
3. Does the Swift compiler tell you for which candidates its heart swings?

**Comment by ephread** [comment]
Closing inactive issue.
