### ISSUE TITLE
how to add instructions for bar button item?

### ISSUE THREAD

**Issue by mouli457** [ephread/Instructions#190]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. (e. g. I'm always frustrated when […])

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ephread** [comment]
A [simple search](https://github.com/ephread/Instructions/issues?utf8=%E2%9C%93&q=UITabBar+OR+UINavigationBar+OR+UIBarButtonItem+) yields the answers you're looking for. #31 is good start.
