### ISSUE TITLE
Swift 4.2 Compiler Error when Archiving for release to App Store.

### ISSUE THREAD

**Issue by Dragonspell99** [ephread/Instructions#192]
**Describe the bug**
When archiving my project for a release to the App Store, I receive the following error (I'm only including a portion of it here for brevity):
```
<unknown>:0: error: fatal error encountered while reading from module 'Instructions'; please file a bug report with your project and the crash log
<unknown>:0: note: compiling as Swift 4.1.50, with 'Instructions' built as Swift 4.2.1 (this is supported but may expose additional compiler issues)

*** DESERIALIZATION FAILURE (please include this section in any bug report) ***
could not deserialize type for '_': could not deserialize type for 'windowLevel': declaration is not a nominal type
Cross-reference to module 'UIKit'
... Level

0  swift                    0x000000011114159a PrintStackTraceSignalHandler(void*) + 42
1  swift                    0x0000000111140d4e SignalHandler(int) + 302

...

3.	While deserializing SIL vtable for 'OverlayManager' in module 'Instructions'
error: Abort trap: 6
```

**Additional context**
Per issue #181, I tried using the `swift4` branch as follows (excerpt from my Podfile):
```
pod 'Instructions', :git => 'https://github.com/ephread/Instructions.git', :branch => 'swift4'
```

I cleaned the build folder before recompiling and I'm still getting the above error.

Any help would be greatly appreciated.

**Comment by astrokin** [comment]
I've faced with this issue too

**Comment by astrokin** [comment]
I've multiple target Xcode project and noticed that one target finally can be archived for the AppStore. And the only difference was `SWIFT_OPTIMIZATION_LEVEL` 

change from *Optimize for Speed:* to *Optimize for Size:* make it works

**Comment by Dragonspell99** [comment]
@astrokin A thousand thanks for your answer! I can't believe it but your suggestion helped and I was finally able to submit the app. I looked everywhere and tried all kinds of things to get it to work.

I have to ask: how did you find this solution to the problem? I would never have thought of changing compiler optimizations based on the error information.

**Comment by astrokin** [comment]
I was lucky to change SWIFT_OPTIMIZATION_LEVEL because had a lot of headaches before. This project settings is very powerful and can do massive transformation of your code under the hood.

**Comment by ephread** [comment]
@Dragonspell99 That's really peculiar, I'll check if I can reproduce the issue but it really looks like a bug in the toolchain rather than an issue with Instructions.

@astrokin I'm glad you jumped in and offered a workaround, thanks a lot!
