### ISSUE TITLE
Edge-case where CoachMark is out of bounds

### ISSUE THREAD

**Issue by mingsai** [ephread/Instructions#194]
**Describe the bug**
In some edge cases, the Instruction view appears outside of the screen bounds. 

**To Reproduce**
Enclose a container view within a UIView (make it near the bottom of the screen)

**Expected behavior**
Instruction view should appear within screen bounds by default

**Screenshots**
See the video - https://youtu.be/IHgW8DuGLn8

**Environment:**
 - Device: iPhone 6s Plus
 - iOS version : 12.2

**Additional context**
The right thing happens in most cases but not always. I am using a custom object to manage the interactions between my view controllers and the coach marks controller.

```swift
//
//  MNGAppInstructionController.swift
//  bch
//
//  Created by Tommie N. Carter, Jr., MBA on 1/21/19.
//  Copyright © 2019 MING Technology. All rights reserved.
//

import Instructions
import UIKit

class MNGAppInstructions: NSObject, CoachMarksControllerDataSource, CoachMarksControllerDelegate  {
	static let shared 		= MNGAppInstructions()
	let controller 			= CoachMarksController()
	var dataViews 			= [UIView]()
	var dataTexts 			= [String]()
	private override init() {
		super.init()
		controller.delegate = self
		controller.dataSource = self
		controller.overlay.blurEffectStyle = .dark
		controller.overlay.allowTap = true
		controller.overlay.allowTouchInsideCutoutPath = true
	}
	func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkViewsAt index: Int, madeFrom coachMark: CoachMark) -> (bodyView: CoachMarkBodyView, arrowView: CoachMarkArrowView?) {
		
		let coachViews = coachMarksController.helper.makeDefaultCoachViews(withArrow: true, arrowOrientation: coachMark.arrowOrientation)
		//☑️✓
		coachViews.bodyView.hintLabel.text = self.dataTexts[index]
		coachViews.bodyView.nextLabel.text = "☑️"
		//check appearance
		//let proposedView = (bodyView: coachViews.bodyView, arrowView: coachViews.arrowView)
		
		
		return (bodyView: coachViews.bodyView, arrowView: coachViews.arrowView)
	}
	func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkAt index: Int) -> CoachMark {
		return coachMarksController.helper.makeCoachMark(for: self.dataViews[index])
	}
	func numberOfCoachMarks(for coachMarksController: CoachMarksController) -> Int {
		return self.dataViews.count
	}
	func shouldHandleOverlayTap(in coachMarksController: CoachMarksController, at index: Int) -> Bool {
		//self.dataViews[index].resignFirstResponder()
		coachMarksController.stop()
		return true
	}
}

```
With usage ...
```swift
private let helper = MNGAppInstructions.shared.controller

override func viewWillDisappear(_ animated: Bool) {
		super.viewWillDisappear(animated)
		self.performHideHelpAction()
	}
	override func viewDidAppear(_ animated: Bool) {
		super.viewDidAppear(animated)
		self.performShowHelpAction()
	}
	@objc func performHideHelpAction(_ sender:Any?=nil){
		guard UserDefaults.standard.bool(forKey: AppSettingKeys.helpRequestedScene3Key.rawValue) else { return }
		UserDefaults.standard.set(false, forKey: AppSettingKeys.helpRequestedScene3Key.rawValue)
		self.helper.stop(immediately: true)
	}
	@objc func performShowHelpAction(_ sender:Any?=nil){
		guard UserDefaults.standard.bool(forKey: AppSettingKeys.helpRequestedScene3Key.rawValue) else { return }
//		MNGAppInstructions.shared.dataViews = [self.searchBox, self.subHeaderMenu, self.containerView, self.closeMenu]
		MNGAppInstructions.shared.dataTexts = ["Tap to filter results", "Shows the number of results","Result list, tap to see detailed information", "Tap to close this scene and return for another search"]
		self.helper.start(in: .window(over: self))
	}
```

**Comment by mingsai** [comment]
Since I can get a reference to the calling UIView where I see this issue, it seems like a good solution might be to instruct the controller to output a CoachMark above the view in this case. Not seeing how to do that explicitly. I will double check the samples in search of a solution. Grateful for any input.

**Comment by mingsai** [comment]
For anyone else following. Here is my solution. Added a tag to the problematic view and changed arrowOrientation for this edge-case. I guess I could also use frame logic to classify the location. Best of all would be if I could just use CoreGeometry methods to determine when the cm frame is offscreen and adjust based on that... I'll look into it further.

```
func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkAt index: Int) -> CoachMark {
	var cm = coachMarksController.helper.makeCoachMark(for: self.dataViews[index])
	if self.dataViews[index].tag == 86 {
		cm.arrowOrientation = .bottom
	}
	return cm
}
```

**Comment by ephread** [comment]
Hey @mingsai, thanks for opening the issue. And thanks for the video, it's appreciated!

It's similar in nature to #152, which is referenced in #130. As you suspect, it's a rather complex edge case. The engine layout could certainly be improved to handle all these edge cases, but I'm not sure it's worth the effort. These cases are all variations of the same thing: a view with its origin in the upper half of the screen, with a height covering almost all the vertical space remaining.

Depending on the case, you can either force the coach mark to display above/under the cutout or ask Instructions to display the coach mark over the cutout by [setting the appropriate values on `CoachMark`](https://github.com/ephread/Instructions#customizing-how-the-coach-mark-will-show).

Your suggestion can be achieved by setting `displayOverCutoutPath` to `true`.
