### ISSUE TITLE
Coach marks showing only last frame ?

### ISSUE THREAD

**Issue by vgvishesh23113** [ephread/Instructions#195]
**Describe the bug**
i am trying to add multiple coach marks but the frame displayed is only the last one?
i will post a link to my question on stackoverflow . Could anyone provide some insights ? Maybe I am doing something wrong?

https://stackoverflow.com/questions/54290193/ios-swift-coach-marks-walk-through-instructions-misbehaving?noredirect=1#comment95403457_54290193

and is it possible to add coach marks on an action, for example i want user to tap on a button and then add a coach mark on the new view? or something along those lines?

**To Reproduce**
```swift
let coachMarksController = CoachMarksController()
let pointOfInterest = UIView()

override func viewDidLoad() {
    super.viewDidLoad()
    self.navigationController?.navigationBar.barTintColor = UIColor(red: 139/255, green: 26/255, blue: 137/255, alpha: 1.0)
    self.navigationController?.navigationBar.titleTextAttributes = [NSAttributedString.Key.foregroundColor: UIColor.white]
    self.navigationController?.navigationBar.tintColor = .white
    self.navigationItem.backBarButtonItem?.title = "Back"
    checkForVolume()
    self.coachMarksController.dataSource = self

    pointOfInterest.frame = CGRect(x: 10, y: 30, width: 30, height: 50)
    coachMarksController.restoreAfterChangeDidComplete()
    coachMarksController.prepareForChange()
    pointOfInterest.frame = CGRect(x: 140, y: 30, width: 130, height: 50)
    coachMarksController.restoreAfterChangeDidComplete()
    coachMarksController.prepareForChange()
    pointOfInterest.frame = CGRect(x: 330, y: 25, width: 35, height: 40)
    coachMarksController.restoreAfterChangeDidComplete()
    coachMarksController.prepareForChange()        
}
```

**Expected behavior**
coach marks go from mentioned frame to frame upon tap

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Environment:**
 ios 12
swift 4.2

**Additional context**
and when i use

 coachMarksController.flow.pause()

 along with 

coachMarksController.flow.resume()

 the screen just freezes with overlay but no coach mark at all

**Comment by ephread** [comment]
Thanks for creating the issue @vgvishesh23113. I don't understand what you're trying to do. Here are some pointers, though:

1. Instructions doesn't support displaying multiple coach marks at once.
2. You need to provide frames by returning a `CoachMark` in the appropriate `dataSource` method (specifically `coachMarksController(_:,index:) -> CoachMark`), you can't provide them it in a declarative way.
3. You change the frame of your view three times in `viewDidLoad`. The layout pass doesn't occur between each frame change and certainly not long after `viewDidLoad` returns, hence only `CGRect(x: 330, y: 25, width: 35, height: 40)` will be taken into account.
4. `restoreAfterChangeDidComplete()` and `prepareForChange()` are not used properly. First, `prepareForChange` should be called before `restoreAfterChangeDidComplete` and before any change is made. Second, I'm not sure they do what you're looking for. These two methods tell Instructions to hide the current coach mark (`prepareForChange`) and then, call the `dataSource`/`delegate` to retrieve relevant data and update the position of the current coach mark (`restoreAfterChangeDidComplete`). Besides, these won't do much if they are called within `viewDidLoad`, as the flow must be started.

**Comment by vgvishesh23113** [comment]
if i cant change the frame in viewdidLoad then what shall be approach to declare the series of frame where coach mark should be present

**Comment by ephread** [comment]
> I AM TRYING TO create a walkthrough for an app and the plan is when one coach mark is tapped on, it changes frame and goes to next one, and show next one and so on. Can this not be achieved by this ?

It can, that's actually the purpose of the library.

> if i cant change the frame in viewdidLoad then what shall be approach to declare the series of frame where coach mark should be present

You should implement the appropriate methods in `dataSource`, as explained in this [section](https://github.com/ephread/Instructions#data-source) of the README, or shown in the default example. [Here for the default example](https://github.com/ephread/Instructions/blob/master/Examples/Example/Sources/Core/View%20Controllers/Basic%20Examples/DefaultViewController.swift) and [there for the base class from which the default example inherits](https://github.com/ephread/Instructions/blob/master/Examples/Example/Sources/Core/View%20Controllers/ProfileViewController.swift).

The [README](https://github.com/ephread/Instructions#usage) and the [Examples](https://github.com/ephread/Instructions/tree/master/Examples) directory (which contains a demo app) cover the different use cases very thoroughly.
