### ISSUE TITLE
delay function is never used

### ISSUE THREAD

**Issue by kaandedeoglu** [ephread/Instructions#2]
the function

``` swift 
public func delay(delay:Double, closure:()->())
```

in `Instructions.swift` is never used within the project.

**Comment by kaandedeoglu** [comment]
hint hint - the same file also has semi-colons after constant declarations :v:

**Comment by ephread** [comment]
Haha, some Objective-C reflexes are still around. It's not that easy to constantly jump between different codebases. :) Thanks again!
