### ISSUE TITLE
Rename `datasource` to `dataSource`

### ISSUE THREAD

**Issue by shergin** [ephread/Instructions#20]
The variant `dataSource` is more convenient on iOS.

Thanks!

**Comment by ephread** [comment]
Oh yeah, I don't know what I was thinking. I was absolutely certain it was spelled `datasource` throughout UIKit. Thanks, I'll correct this in the near future. :)

**Comment by shergin** [comment]
I just mention it because I spend couple of extra minutes investigating bug caused unusual spelling of "dataSource".
Thank you for your work!
