### ISSUE TITLE
Carthage update Issue

### ISSUE THREAD

**Issue by thejbix** [ephread/Instructions#202]
Trying to update to Instructions version to 1.2.2 using Carthage.  The checkout fails returning this error. It may be worth noting this started occurring after updating Xcode to version 10.2 with the Swift 5.0 release
`A shell task (/usr/bin/env git clone --quiet https://github.com/ephread/InstructionsSnapshots.git /Users/user_name/Documents/.../Carthage/Checkouts/Instructions/Examples/Example/Snapshot\ Tests/Supporting\ Files/Snapshots) failed with exit code 128:
git-lfs filter-process: git-lfs: command not found
fatal: the remote end hung up unexpectedly
warning: Clone succeeded, but checkout failed.`

**Environment:**
Xcode 10.2
Swift 5.0
Carthage 0.32.0

**Comment by ephread** [comment]
Hi @thejbix, you don't have [Git LFS](https://git-lfs.github.com/) installed. It's required because of the submodule storing the snapshot tests and sadly, there's no way to tell Carthage to ignore submodules.

**Comment by thejbix** [comment]
Great, that resolved my issue.  

Thanks
