### ISSUE TITLE
Is there a way to set the whole view as a "next" button?

### ISSUE THREAD

**Issue by igormuba** [ephread/Instructions#203]
I find it a bit unintuitive that the user should tap the coachMark to go to the next instruction. I have found [this piece of code on the examples](https://github.com/ephread/Instructions/blob/master/Sources/Instructions/Extra/Default%20Views/CoachMarkBodyDefaultView.swift) that seems to implement something to personalize where to click to skip, but couldn't replicate. I can inherit "CoachMarkBodyView" but then when I inherit "UIControl" to return "self" on "nextControl" it gives me an error that I cannot inherit "UIControl"

How can I make the whole screen clickable to skip the mark?

**Comment by k0mach1** [comment]
Hi, maybe I can help you.

All you have to do is very simple, just write

```swift
coachMarksController.overlay.allowTap = true
```

before calling **coachMarksController.start** in your ViewController.

**Comment by k0mach1** [comment]
@igormuba 
Hi, maybe I can help you.

All you have to do is very simple, just write

```swift
coachMarksController.overlay.allowTap = true
```

before calling **coachMarksController.start** in your ViewController.
