### ISSUE TITLE
Coachmarksplaced behind notch in landscape app on iphone x. 

### ISSUE THREAD

**Issue by kallipigous** [ephread/Instructions#205]
When I use instructions on a landscape app, coachmarks are sometimes place with reference to the whole window not the safe area that takes into account the notch.

**Comment by ephread** [comment]
Hi @kallipigous, would you be able to set up a sample project demonstrating the issue? Perhaps it's related to #169?

**Comment by kallipigous** [comment]
I’m out of the country for a bit but I’ll try and do so on my return. I temporarily fixed it by making the coachmark thinner.

**Comment by ephread** [comment]
I was able to reproduce this really old issue a few hours ago. I'll investigate.

**Comment by ephread** [comment]
Sorry it took so long to fix this, I don't really understand how I could miss this in the first place.
