### ISSUE TITLE
Several warnings still showing

### ISSUE THREAD

**Issue by AdamM-FC** [ephread/Instructions#206]
I have downloaded the latest version of Instructions and I can see there are 5 warnings regarding deprecations. See screenshot. Will there be a new release soon to resolve these warnings?

**Screenshots**
![Screenshot 2019-05-01 at 16 39 50](https://user-images.githubusercontent.com/49152817/57025750-f7502c00-6c2f-11e9-9cd2-7f9c119ef2ed.png)

**Comment by ephread** [comment]
Hi @AdamM-FC, per #201:

> Yeah, Instructions issues warnings for deprecated things, even for unexposed calls. That's because I need to mark certain properties and methods as deprecated, so that developers will know they have to use the new properties/methods. The side effect is that, if I'm to keep deprecated stuff working during the transition phase, I need to call them from inside the library, hence the warnings.
> 
> If you treat warnings as errors, the project will not build for that reason. You may be able to use :inhibit_warnings => true in your Podfile, however.

If you use Carthage, I'm not certain there's a way to inhibit these warnings, sadly.

**Comment by AdamM-FC** [comment]
Ah okay, thanks for the info
