### ISSUE TITLE
Carthage update issue

### ISSUE THREAD

**Issue by silviagaluzzi** [ephread/Instructions#207]
Hi, I'm having this error running carthage update:

A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/ephread/Instructions.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/GALSIV/Library/Caches/org.carthage.CarthageKit/dependencies/Instructions)) failed with exit code 1

when I tried last time (a couple of days ago) everything was ok, and nothing changed on my project

thanks for your attention

**Comment by ephread** [comment]
Hey @silviagaluzzi, that's strange. Would you be able to provide the full section of the Carthage log, dealing with the build of Instructions? It's a bit hard to know what's going on here.

**Comment by silviagaluzzi** [comment]
Hi, I can't send you the log because it's not a build failure, it's a checkout/fetch error
It doesn't get to building the framework, it stops when fetching it from github

As I wrote it's strange because we are using Instructions for a long time and we never had this problem.

thank you!

**Comment by silviagaluzzi** [comment]
I fixed following this:

https://stackoverflow.com/questions/45504896/how-to-clear-carthage-cache


ty for your attention!

**Comment by ephread** [comment]
Awesome, I'm glad you solved the issue!
