### ISSUE TITLE
Wrap or remove access to `UIApplication.sharedApplication()`

### ISSUE THREAD

**Issue by shergin** [ephread/Instructions#21]
The reason is:
```
+ (UIApplication *)sharedApplication NS_EXTENSION_UNAVAILABLE_IOS("Use view controller based solutions where appropriate instead.");
```

Access to `UIApplication.sharedApplication()` unavailable inside iOS extensions and because of this library cannot be used for instance for guide inside custom keyboard.

**Comment by ephread** [comment]
Good point. I actually never thought about that particular case. The current code calling `UIApplication.sharedApplication()` is only used to make sure the “Skip button” doesn't overlap the view. It even uses a magic value… sigh… it was bound to break one way or another. :) I'll look into it, thanks!

**Comment by shergin** [comment]
Unfortunately, as I know, there is no predefined #define variable of something like this to test for such king of availability issues. (

You can take a look at similar topic here: https://github.com/AFNetworking/AFNetworking/issues/2119

But, I hope, we can:
 * Just avoid using "sharedApplication" object.
 * Use something like this (I haven't tested it yet):

```
extension UIApplication {
    func safeSharedApplication() -> UIApplication? {
        guard UIApplication.respondsToSelector("sharedApplication") else {
            return nil
        }

        guard let unmanagedSharedApplication = UIApplication.performSelector("sharedApplication") else {
            return nil
        }

        return unmanagedSharedApplication.takeRetainedValue() as? UIApplication
    }
}
```

**Comment by ephread** [comment]
Thanks for the tip. ;) For now, I'll just test whether `UIApplication` responds to `sharedApplication`, it'll be enough, given that this feature is scarcely used. But I'll play with keyboards and extensions in the future!

**Comment by shergin** [comment]
Thank you!
But... Unfortunatelly, it will not work. (
Compiler simply can't compile line `UIApplication.sharedApplication()` (even if it inside the `if`-statement and never called), because of this we have to use something like `UIApplication.performSelector("sharedApplication")`.

**Comment by ephread** [comment]
Ah, I'm sorry, I'm not familiar at all with the way extensions work on iOS. I thought `NS_EXTENSION_UNAVAILABLE_IOS` would somehow make a difference at runtime rather than compile-time :sweat:. Tell you what, would you be able to make a pull request, fixing the problem?

That would be much easier since, at the moment, I'm not able to test the library within the constraints of the app extension environment. I could throw another fix, using `performSelector`, as you suggested, but I'd be doing a blind guess and we might end up ping-ponging each other!

**Comment by ephread** [comment]
I've been tinkering with the ability to use Instructions in app extensions during the last few days. In the end, I've taken a cautious approach here and removed the (mostly unnecessary) call entirely.

**Comment by ephread** [comment]
Version 0.5.0 is out with full support of App Extensions.
