### ISSUE TITLE
Could not find module 'Instructions' for architecture 'i386'; found: x86_64

### ISSUE THREAD

**Issue by WhiteEagleEye** [ephread/Instructions#210]
**Describe the bug**

I'm added Instructions manually by following given steps but it is saying "Could not find module 'Instructions' for architecture 'i386'; found: x86_64" 

Xcode 10.2.1

**Comment by ephread** [comment]
I'm going to need more information to help you. Where does this error message appear, in the build log? Does Instructions.framework build correctly in the first place?

**Comment by WhiteEagleEye** [comment]
I'm able to resolve this issue by making Build Active Architecture Only NO for both debug and release
