### ISSUE TITLE
Not able to download the latest version (1.3.1) by pod install

### ISSUE THREAD

**Issue by narendra-ct** [ephread/Instructions#211]
Hello, 
I tried to install by pod 'Instructions', '~> 1.3.1' , but throwing error on pod install and if try with pod 'Instructions' , downloading 1.2.2 version.  Attached screenshot. 
![Screen Shot 2019-05-21 at 4 58 00 PM](https://user-images.githubusercontent.com/5906472/58092523-f0db2180-7be9-11e9-9f98-7a839bc0c977.png)

**Comment by ephread** [comment]
Hey @narendra-ct, have you tried to update your local spec?
Either through `pod repo update` or `pod install --repo-update`.

1.3.1 has been [pushed to the master repo](https://cocoapods.org/pods/Instructions).

**Comment by narendra-ct** [comment]
@ephread, My bad, it works after pod repo update.
Thanks.
