### ISSUE TITLE
Remove Overlay

### ISSUE THREAD

**Issue by chamitha** [ephread/Instructions#212]
Hi there. Is there a way to configure the framework to not add an overlay? I know I can set the overlay background colour to clear visually mimic this but not including it in the first place would be preferred. Thanks!

**Comment by ephread** [comment]
Hey @chamitha, sorry for the late response. Sadly, it's not at the moment. Are you trying to achieve something in particular?

**Comment by chamitha** [comment]
Thanks @ephread for the reply. I was hoping to maintain the screen as active and responsive whilst the popover is displayed so the user is not forced to dismiss it before continuing the use the screen. This is the behaviour in the YouTube app for example where the popover behaves like a tooltip and the screen is fully responsive. Granted there will be some complexity dismissing the popover when the user clicks anywhere else on the screen if no overlay view is present to capture this event.

**Comment by ephread** [comment]
Alright, good point; I'll add a new flag in the next version to let the overlay be non blocking; you'll be able to achieve what you want by setting the overlay's color to `.clear` and setting that new flag to `true`.

**Comment by chamitha** [comment]
Perfect, thanks.

**Comment by chamitha** [comment]
Hi @ephread. Any update on this? I can give it a go if you haven't already started on it.

**Comment by noumantariq008** [comment]
Hi @ephread. Any update on this?
I wanted to achieve the same thing.

**Comment by chamitha** [comment]
Is this yet to be released?

**Comment by ephread** [comment]
Yes, this hasn't been released yet.
