### ISSUE TITLE
iPhone XS Max positioning bug

### ISSUE THREAD

**Issue by h36ahmed** [ephread/Instructions#215]
**Describe the bug**
iPhone XS Max - the positioning of the body view is off. It's not centered properly as expected. All other device screen sizes work perfectly. Its off by -10px.

**To Reproduce**
Create some views in views controller and run iphone xs max on simulator.

**Expected behavior**
The cutouts need to be precise without adjusting manually.

**Screenshots**
![image](https://user-images.githubusercontent.com/13081913/63359285-77fb7b00-c33a-11e9-856f-3957188ec76c.png)

**Environment:**
 - Device: iPhone XS Max
 - iOS version: 12.4
 - Dependency Manager: CocoaPods

**Additional context**

**Comment by ephread** [comment]
Hey @h36ahmed, would you be able to provide a sample project demonstrating the issue?

**Comment by ephread** [comment]
I fixed a similar problem on iPad, so I'm hoping it fixed this one as well. Since there hasn't been a lot of activity on this issue, I'm closing it.
