### ISSUE TITLE
Custom Cutout View

### ISSUE THREAD

**Issue by tarun885** [ephread/Instructions#216]
**Custom Cutout View**
How can i create a cutout view shown as below image?

<img width="127" alt="Screenshot 2019-09-07 at 1 07 43 AM" src="https://user-images.githubusercontent.com/25946509/64455730-04b08200-d10c-11e9-8dde-7286a3ba0a95.png">

**Comment by ephread** [comment]
Hi @tarun885, it's sadly impossible as of the current version. It may be implemented in the future, but it's low priority for now, sorry.

**Comment by tarun885** [comment]
@ephread, Thanks for the reply. I'll be looking forward to the functionality in future updates.

**Comment by ephread** [comment]
Cheers!
