### ISSUE TITLE
Unable to install version 1.3.1 with Carthage

### ISSUE THREAD

**Issue by Hirobreak** [ephread/Instructions#217]
**Describe the bug**
I'm using carthage to integrate Instructions within my project, suddenly when I made `carthage update Instructions --platform iOS` I get the following error:

`
Smudge error: Error downloading ReferenceImages_64/InstructionsSnapshotTests.DefaultExampleSnapshotTests/testFlowInController__i0_o1_controller_iPhone11_4_375x812@3x.png (85eb0ea72da524fa6a2fa4aecadfef26700b0bb92f08104e06c449b788ed4f73): batch response: This repository is over its data quota. Purchase more data packs to restore access.
`
 
**To Reproduce**
Update Instructions with Carthage running:  `carthage update Instructions --platform iOS`

**Expected behavior**
To successfully pull and build Instructions from git using Carthage

**Environment:**
 - Device: MacOS 
 - Dependency Manager: Carthage

**Additional context**
I have to go back to version 1.2.0 in order to build `Instructions` but it's outdated with `Swift 4`

**Comment by edpelesh** [comment]
Same for me, it is the Github restriction of git-lfs quota.

**Comment by ephread** [comment]
I am really, really sorry about that. Using LFS for snapshots turned out to be a bad idea.

@Hirobreak, @edpelesh can you try installing from master directly? The LFS references should have been removed in `master/HEAD`. If you still can't install it, I'll try to fix that issue as soon as possible.

**Comment by edpelesh** [comment]
Installing from the master fixed the problem. Sorry, forgot to let you know.
Thanks for the fix.

**Comment by derekgraham** [comment]
Is there more detail on "installing from master directly"?  Or is there a way I can donate some LFS datapaks to make this go away?

**Comment by derekgraham** [comment]
I changed my carthage cartfile line for Instructions to:
github "ephread/Instructions" "master"

and that worked. thanks!

**Comment by chamitha** [comment]
Does this mean LFS will no longer be a required pre-requisite for installation?

**Comment by ephread** [comment]
@derekgraham sorry I didn't get back to you sooner, I'm glad you found out by yourself!

@chamitha yup!

1.4.0 is out now, and removes the dependency on LFS.
