### ISSUE TITLE
A number of Deprecations are appearing in Xcode 11

### ISSUE THREAD

**Issue by ethanwa** [ephread/Instructions#219]
<img width="311" alt="Screen Shot 2019-09-13 at 10 39 06 PM" src="https://user-images.githubusercontent.com/1653780/64902570-bead6e00-d677-11e9-8883-a97955fbeba2.png">

**Comment by ephread** [comment]
Hi @ethanwa, per #201:

> Yeah, Instructions issues warnings for deprecated things, even for unexposed calls. That's because I need to mark certain properties and methods as deprecated, so that developers will know they have to use the new properties/methods. The side effect is that, if I'm to keep deprecated stuff working during the transition phase, I need to call them from inside the library, hence the warnings.
> 
> If you treat warnings as errors, the project will not build for that reason. You may be able to use :inhibit_warnings => true in your Podfile, however.

If you use Carthage, I'm not certain there's a way to inhibit these warnings, sadly.

1.4.0 will remove them, but I'm not sure when it will be published.

**Comment by ephread** [comment]
1.4.0 is out and warnings are gone!
