### ISSUE TITLE
Please add support for Swift Package Manager (Dependencies)

### ISSUE THREAD

**Issue by ethanwa** [ephread/Instructions#220]
Many people will be moving away from CocoaPods and Carthage and using Swift Package Manager (Dependencies). Can you please add support? Thank you!

**Comment by ephread** [comment]
Hi @ethanwa, it's been on the roadmap for a long time but it's not possible currenlty. SwiftPM sadly doesn't support resources.

The last time I checked was June this year, are resources supported now?

**Comment by ephread** [comment]
Since the default coach marks are now hand drawn and no longer use images, I might be able to add SwiftPM support. I will have a look in the coming days.

**Comment by ethanwa** [comment]
This would be awesome, thanks so much!!

**Comment by ephread** [comment]
🎉 I'm happy to announce that Swift Package Manager should now be supported by Instructions (only in `master` for now, I'll create the next release over the next few days).

**Comment by ethanwa** [comment]
Any chance you could push this to a main release now? Sorry to bug you! Thanks!

**Comment by ephread** [comment]
Yeah, sorry. 😕 I need to rewrite a bit of the README and I haven’t had the chance to do it. I’ll try to do it during the next two weeks.

The release isn’t likely to be much different from `master` though.

**Comment by ephread** [comment]
@ethanwa, so I'm currently working on the next release, but I now feel it's better if I go straight to 2.0.0 and rename the properties I've wanted to rename for a while. It should come out in the next few days (perhaps even today), but it won't look like `master`, I take back what I said. Sorry about that.

The migration shouldn't be too big though, it's mostly a bunch of properties renamed. The compiler should be giving hints.

**Comment by ephread** [comment]
2.0.0 was released!
