### ISSUE TITLE
0 is not an invalid value for numberOfCoachMarksForCoachMarksController

### ISSUE THREAD

**Issue by chamitha** [ephread/Instructions#221]
`CoachMarksController.start` logs the statement `startOn: the dataSource returned an invalid value for numberOfCoachMarksForCoachMarksController(_:)` to the console if `numberOfCoachMarks` in the data source returns 0. However this is misleading as 0 is a valid value. I.e there are no coach marks. 
This message should only be logged if `numberOfCoachMarks` returns a value less than 0 or log a more accurate message such as `startOn: the dataSource returned 0 for numberOfCoachMarksForCoachMarksController(_:)`.

**Comment by ephread** [comment]
Hey @chamitha, that's a good point. I suspect there was a reason (that I forgot) for the message to be logged, though. I'll have a look and decide whether to change or keep the behaviour!

**Comment by chamitha** [comment]
No worries. Not a high priority. Just threw me a bit that I might be doing something wrong!

**Comment by ephread** [comment]
All good. 1.4.0 has an updated message, which warns about using 0 without using a scary terminology. I'm keeping it as a warning, because, like not setting the `dataSource`, it's an easy thing to miss. 🙂

```swift
if numberOfCoachMarks < 0 {
    fatalError("dataSource.numberOfCoachMarks(for:) returned a negative number.")
} else if numberOfCoachMarks == 0 {
    print("[WARNING] dataSource.numberOfCoachMarks(for:) returned 0.")
    return
}
```
