### ISSUE TITLE
DarkMode support for iOS 13+

### ISSUE THREAD

**Issue by nastasiupta** [ephread/Instructions#223]
**Is your feature request related to a problem? Please describe.**
I need Dark Mode support for your framework. 
Is not a problem... but is nice to have

**Describe the solution you'd like**
Well, a good way is just to have a flag to disable dark mode, but by default, this should be supported.

**Describe alternatives you've considered**
Access to setup the background colors

**Additional context**
-

**Comment by ephread** [comment]
Hey @nastasiupta, Instructions should work out of the box with Dark Mode, as long as you provide custom views and override the default overlay color.

In the near future, I'll plan to get rid of the current image-based default views and replace them with views drawn in code. I'll be sure to include defaults for both interface styles.

**Comment by ephread** [comment]
Full Dark Mode support has landed in `master`. It includes properly re-rendering the layers when the interface style is updated and the ability to customize the colors of the default coach marks.

I still have a couple of other things to add for the next release, but it should come out soon !
