### ISSUE TITLE
overlay.blurEffectStyle not working

### ISSUE THREAD

**Issue by ciathyza** [ephread/Instructions#229]
I'm trying to add a blur effect to the coachMarksController but it doesn't work, e.g.:

`_coachMarksController.overlay.blurEffectStyle = .prominent`

Results in the background overlay not showing at all and only the text is visible but misplaced on the screen. Any ideas why this wouldn't work?

**Comment by ephread** [comment]
Hey @ciathyza, I don't really know, I can't reproduce the issue. Is it happening as well if you run the example project on your setup?

**Comment by ephread** [comment]
Indirectly related to #231, the issue happens when using a Scene Delegate.

**Comment by ephread** [comment]
@ciathyza is this still happening in the latest version (2.0.0)?

**Comment by chamitha** [comment]
@ephread I'm seeing this issue too in v2.0.0. All is well without setting the `blurEffectStyle`.

**Comment by ephread** [comment]
@chamitha does that happen with the example project? On which device/simulator? Do you have a minimal projects to share? I'd really like to get to the bottom of this, but I've been unable to reproduce the issue so far. Maybe I'm missing something obvious here.

**Comment by chamitha** [comment]
@ephread It seems like the issue occurs if the `CoachMarksController` is started in the context of the view controller. However starting it in the context of the window as per the Readme works fine. Let me know if you need further info or a sample project.

```
        // This works :)
        coachMarksController.start(in: .window(over: self))

        // This does not work :(
        coachMarksController.start(in: .viewController(self))
```

**Comment by chamitha** [comment]
and for the record I'm using Xcode 11.6 running the iPhone 11 simulator with iOS 13.6

**Comment by ephread** [comment]
> It seems like the issue occurs if the CoachMarksController is started in the context of the view controller. However starting it in the context of the window as per the Readme works fine. Let me know if you need further info or a sample project.

That's an interesting behaviour, thanks for the helping hand @chamitha, it's much appreciated! I'll investigate as soon as possible.
