### ISSUE TITLE
Add a Exit button

### ISSUE THREAD

**Issue by vicajilau** [ephread/Instructions#230]
**Desciption**
Superimpose a button in one of the corners that allows coach marks to stop.

**Graphic proposal**
https://ibb.co/sK1gcWL

**Alternatives considered**
I have considered that the sentence can be used to stop the flow:
`self.coachMarksController.stop(immediately: true)`
But I don't know how Instructions works to overlay a button on it. Maybe you can give me an orientation and I could do it myself

**Comment by ephread** [comment]
Hi @vicajilau, the [_Skip Control_](https://github.com/ephread/Instructions#let-users-skip-the-tour) may be what you are looking for.

**Comment by vicajilau** [comment]
> Hi @vicajilau, the [_Skip Control_](https://github.com/ephread/Instructions#let-users-skip-the-tour) may be what you are looking for.

It was very easy, excellent job
