### ISSUE TITLE
Keep podspec version at iOS 9

### ISSUE THREAD

**Issue by jlubeck** [ephread/Instructions#233]
I noticed that your project works perfectly on iOS 9. I understand that on your Readme you specify support for iOS 11+ so that you wouldn't have to support bugs on lower versions, but is it possible that you at least keep the podspec at 9 instead of the curren 10? Otherwise it can't even be installed via Cocoapods.

I understand iOS 9 is pretty old, but unfortunately a large number of iPad minis and iPad 3s can't go above iOS 9.

Thank you.

**Comment by ephread** [comment]
Yeah, I guess it wouldn't hurt. I'll update the podspec in a future release!

**Comment by jlubeck** [comment]
Great! Thank you

**Comment by ephread** [comment]
I guess this can be closed now! 2.0.0 should be importable and runnable in iOS 9 projects.
