### ISSUE TITLE
allowTouchInsideCutoutPath not working on iPad Pro 11"

### ISSUE THREAD

**Issue by clueth** [ephread/Instructions#234]
**Describe the bug**

I'm using the allowTouchInsideCutoutPath=true in combination with disableOverlayTap=false. Works with each device but the iPad Pro 11" (2nd Gen). It is not possible to click inside the cutout area.

**To Reproduce**

You can use your code example from TransitionFromCodeViewController to redroduce the issue (the tap on the button does not work)

**Expected behavior**

The tap on the button should click the button like on other devices.
**Screenshots**

**Environment:**
 - Device: 
iPad8,3
 - iOS version: 
13.4.1
 - Dependency Manager: 
CocoaPods

**Additional context**

**Comment by ephread** [comment]
Hey @clueth, thanks a lot for reporting the issue, I investigated and I'm pretty sure it's been there since iOS 13 came out. That's a really nasty bug. I'm working on a fix and I'll update the test matrix.

**Comment by clueth** [comment]
Thank you very much for the fast fixing!
