### ISSUE TITLE
How to change background of hint/next labels?

### ISSUE THREAD

**Issue by stevehartford** [ephread/Instructions#236]
The rounded background behind the hint label is always solid white and rounded. Other parts can be customized, would be great to be able to customize or at least remove entirely (make clear). Any suggestions? Thanks.

**Comment by ephread** [comment]
Hi @stevehartford, you can [provide custom views](https://github.com/ephread/Instructions#providing-custom-views). The defaults views are not really meant to be customized.

That said, the next version of Instructions will drop the image backgrounds and draw them programmatically instead. You'll be able to customise the background color, the border color and the corner radius.

**Comment by ephread** [comment]
I'm closing since version 2.0.0 lets you customise a few things, see [here](https://github.com/ephread/Instructions#customizing-default-coach-marks).
