### ISSUE TITLE
Not able to set it on navigation items (Left or right)

### ISSUE THREAD

**Issue by shireeshMs** [ephread/Instructions#240]
Is there any way to do this, required, please.

**Comment by ephread** [comment]
Hey @shireeshMs, no there isn't. There was some work done a while ago by an external contributor, but it was never fully merged back as it needed some more work.

It's very low on my priorities sadly.

**Comment by shireeshMs** [comment]
hey thanks a lot, you guys worked it really well, let me take this honour first 😊

I saw that reference and I am able to do on nav item but is there any way to change skip position?

**Comment by ephread** [comment]
You can provide custom constraints, see [here](https://github.com/ephread/Instructions#datasource).
