### ISSUE TITLE
Remove the separator in the coachMarksController

### ISSUE THREAD

**Issue by HebaAtallah** [ephread/Instructions#244]
How to remove the separator line between the nextLabel and the hintLabel, and make the nextLable up a little bit with the makeDefaultCoachViews

**Comment by Gooshy** [comment]
This is a good suggestion especially when setting isUserInteractionEnabled to true.

**Comment by ephread** [comment]
@HebaAtallah @Gooshy if you want to go beyond the capabilities offered by the default coach marks, you can provide your own [custom views](https://github.com/ephread/Instructions#providing-custom-views).
