### ISSUE TITLE
Positioning Coach Mark

### ISSUE THREAD

**Issue by djsomen** [ephread/Instructions#246]
I am often implementing tutorial screens where there are several details on the screen at once. What I would like is the ability to provide a coach mark that can either be placed independent of the cutout, or allow the coach mark to fill the screen so that I can add my own subviews anywhere according to my own constraints. I tried different things but the closest I got was providing a decoration view but unfortunately this is not connected to steps.

**Comment by ephread** [comment]
Related to #23.

I feel it's probably a bit beyond the scope of this library. If you want to display multiple elements at once on the screen and don't attach them to underlying views, it's probably going to be easier to roll out your custom solution.

#23 is on the roadmap though, but it's been for a long time. Maybe I'll tackle this next!

(By the way, it's possible to show a coachmark without the cutout, see [#83](https://github.com/ephread/Instructions/issues/83#issuecomment-261511352))

**Comment by djsomen** [comment]
Appreciate the response @ephread 👍 I came up with a solution for the time being. I grab the persistent overlay from the datasource delegate then if a _step_ has independent elements (ornaments) I want to display then I fade them in and out on willShow/willHide. I hope that helps someone.

```swift
extension MyTutorial: CoachMarksControllerDataSource
{
    func coachMarksController(_ coachMarksController: CoachMarksController, configureOrnamentsOfOverlay overlay: UIView) 
    {
        self.overlay = overlay
    }
}

extension MyTutorial: CoachMarksControllerDelegate
{
    func coachMarksController(_ coachMarksController: CoachMarksController, willShow coachMark: inout CoachMark, beforeChanging change: ConfigurationChange, at index: Int) 
    {
        guard let ornament = steps[index].ornament else { return }

        UIView.transition(with: overlay, duration: 0.25, options: .transitionCrossDissolve, animations:
        {
             self.overlay.addSubview(ornament)
             ornament.edgesToSuperview() //using TinyConstraints
        },
        completion: nil)
    }

    func coachMarksController(_ coachMarksController: Instructions.CoachMarksController, willHide coachMark: Instructions.CoachMark, at index: Int) 
    {
        UIView.transition(with: overlay, duration: 0.25, options: .transitionCrossDissolve, animations:
        {
            self.overlay.removeAllSubViews() //custom implementation
        },
        completion: nil)
    }
}
```

**Comment by ephread** [comment]
Closing because I consider this resolved. Great solution here!
