### ISSUE TITLE
Skip certain coachMark

### ISSUE THREAD

**Issue by mrdavey** [ephread/Instructions#25]
Hi there. Great work on Instructions!

Is there a way to skip a certain coachMark programatically? E.g. getting access to showNextCoachMark().

My use case is:
1) Display keyboard during a coachMark
2) Wait for the user's input
3) Progress to the next coachMark after user has selected 'return' from the keyboard

I would like to skip the current coachMark in step 3, so the next coachMark is displayed after user 'returns'.

**Comment by ephread** [comment]
Thanks @mrdavey!

It's not possible at the moment, but it's planned! That's what the cryptic “Programatic support for transition”, found in the roadmap, refers to. I'll give you a heads up when it'll be ready. :)

**Comment by mrdavey** [comment]
Excellent! I look forward to it!

**Comment by ephread** [comment]
@mrdavey With 0.4.0, you can now skip coach marks and even wait for user input before showing the next one !

You can take a look at the README [here](https://github.com/ephread/Instructions#skipping-a-coach-mark) and [here](https://github.com/ephread/Instructions#piloting-the-flow-from-the-code).

**Comment by mrdavey** [comment]
Love it! Works perfectly as needed. Thank you!
