### ISSUE TITLE
[Breaking][Xcode 13.0 b3]: "error: 'shared' is unavailable in application extensions for iOS:"

### ISSUE THREAD

**Issue by Panajev** [ephread/Instructions#256]
## Describe the bug
Hello @ephread,

When compiling our application, I see the following problem reproduced with the attached sample example (modified the following repository sample... taken the sample from the repo and just reduced it a bit and used the library from SwiftPM and not the precompiled version included before to replicate how we use it in our apps):

$HOME/Library/Developer/Xcode/DerivedData/Instructions_Example-hhbleavuawdnqpbogvbuddnqmepj/SourcePackages/checkouts/Instructions/Sources/Instructions/Core/Public/CoachMarksController.swift:215:48: error: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
            if let windowScene = UIApplication.shared.activeScene {

Note that this was not happening in our app or this sample project with Xcode 13.0 beta 2, it started happening today when I updated to Xcode 13.0 beta 3).

Thank you in advance for your help :)!

Kind Regards,

Goffredo Marocchi

## To Reproduce
Open attached project, resolve SwiftPM dependency, compile project

## Expected behavior
Sample project to compile
[SampleIssue_Proj.zip](https://github.com/ephread/Instructions/files/6826781/SampleIssue_Proj.zip)

## Environment
 - Device: iOS Simulator or Device
 - iOS version: iOS 15.0 beta 3
 - Instructions version: 2.1.0
 - Dependency Manager: SwiftPM

## Additional context
Apple Feedback Reporter bug #: FB9337463
This could be related to this previously closed issue: https://github.com/ephread/Instructions/issues/21 

It seems related to the following change in Xcode 13.0 beta 3 which will require a change in this library and all others which may be affected (use UIApplication.shared.): https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/11

**Comment by Panajev** [comment]
You could close it as I think it is a SwiftPM change. Integrating the library through CocoaPods solves the problem here and passes it down to the next library integrated through SwiftPM.

**Comment by ephread** [comment]
@Panajev Hey there, well that should be an easy fix; you've already done the heavy lifting! Than you so much for providing a example and investigating. I'll try to make the fix over the coming days.

**Comment by kylebrowning** [comment]
Heads up Xcode Beta 5 fixes this.

**Comment by ephread** [comment]
Closing because it fixed itself.
