### ISSUE TITLE
Coach marks on Table view

### ISSUE THREAD

**Issue by madhumb** [ephread/Instructions#257]
## Describe the bug
I would like to implement coach marks on table view.
plan is to show coach marks on some of the cells. I need to scroll to particular item if its not visible and show coach mark on it.

It works fine when all cells are visible. it doesn't work only when I had to scroll and show.

## To Reproduce
Issue is : If cell is not in visible cells, coach mark is not showing up

## Expected behavior
I would like to show coach mark in cell , tap on it to close and scroll to next and show

## Screenshots
I tried using pause and resume. but is how's multiple coach marks
![IMG_7E4606730F7C-1](https://user-images.githubusercontent.com/5220334/126202260-3d12abf2-de99-4d8f-b5cd-f405e88b41a6.jpeg)

## Environment
 - Device: All iPhones 
 - iOS version: 13 and above
 - Instructions version: I use instruction manager .because I have both objective c and swift in it
 - Dependency Manager: none

## Additional context
help me show coach marks on table view.

**Comment by madhumb** [comment]
@ephread  let me know if quick config I'm missing

**Comment by ephread** [comment]
Hey @madhumb, I believe you may find #249 interesting as it sounds like you're having the same issue!

As for the duplicated coach marks, are you pausing in `willShow` or in another delegate method?

**Comment by ephread** [comment]
Closing due to a lack of activity.
