### ISSUE TITLE
CoachMarkBodyView shows on the end of the window

### ISSUE THREAD

**Issue by filipepipeline** [ephread/Instructions#26]
Hey guys,

I'm trying to create a coachmark to a view that has this hierarchy:

UIScollView -> UICollectionView -> UICollectionViewCell -> UIView

When coach marks tries to show it shows below the window, when it should show up on my view.

I needed to use the "gapBetweenCoachMarkAndCutoutPath" to workaround this problem.

**Comment by ephread** [comment]
Hello @filipepipeline, thanks for reporting the issue.

Can you provide me with a screenshot of your collection view or with a minimum project showing the issue? It'll be of great help to understand what's going on!

**Comment by ephread** [comment]
Closing inactive issue.

With 0.4.0 you can now specify the position of the coach mark (Top/Bottom) manually. It might solve your problem.
