### ISSUE TITLE
Next Label Issue on iOS 15

### ISSUE THREAD

**Issue by Parham-dev** [ephread/Instructions#263]
The next label on iOS 15 get truncated. it works fine on iOS 14 and below.
![IMG_2812](https://user-images.githubusercontent.com/8505643/139257275-5126b388-75bd-43e5-8a0a-d8b89836151c.PNG)

**Comment by jamestalano** [comment]
Any updated?

**Comment by ephread** [comment]
@Parham-dev @jamestalano sorry for the late response, it should be fixed in main, thanks to #261. I need to double check a few things and create a release.

**Comment by jamestalano** [comment]
Great Thank you @ephread Could you please let me know the release version?

**Comment by jamestalano** [comment]
I am using Pod and which version can I use to see fixed one? Thanks~ @ephread

**Comment by jamestalano** [comment]
Any update please?

**Comment by ephread** [comment]
@jamestalano point to 'main' in your Podfile and let me know if that solves the issue.

```ruby
pod 'Instructions', :git => 'https://github.com/ephread/Instructions.git', :branch => 'main'
```

**Comment by jamestalano** [comment]
Great It works! Thank you so much!

**Comment by jamestalano** [comment]
Please let me know once you release this fix so that we can use regular version. Thanks

**Comment by ephread** [comment]
[2.1.1](https://github.com/ephread/Instructions/releases/tag/2.1.1) was released on November 16 an should fix the issue. Closing!
