### ISSUE TITLE
Top arrow is not displayed

### ISSUE THREAD

**Issue by vgkanis** [ephread/Instructions#270]
As the title says, the top arrow is not displayed. But, the bottom it is.
The body of the CoachMark is a custom one, but I am using the default arrows.
This screenshot is with the bottom arrow:
![Screenshot 2022-03-24 at 11 23 41 AM](https://user-images.githubusercontent.com/14078589/159885570-3409a7b3-ddce-4d5b-b460-a366a145c530.png)

and this one is with the top arrow:
![Screenshot 2022-03-24 at 11 24 29 AM](https://user-images.githubusercontent.com/14078589/159885626-95b4622a-1892-4a77-bc68-92eca51fbe26.png)

If I use my arrow, then I get the following screenshot
![Screenshot 2022-03-24 at 11 29 44 AM](https://user-images.githubusercontent.com/14078589/159885858-32953f8f-d07b-4dc8-8be1-a4b44c573ae0.png)

Does anybody know how to fix this?

Thank you

**Comment by ephread** [comment]
Hey @vgkanis, sorry for the late response.

That's weird, it's going to be difficult to troubleshoot without having access to the code. Would you be able to provide a sample project showcasing the issue or a few code excerpts?

**Comment by bevanchristian** [comment]
func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkAt index: Int) -> CoachMark {
        var coachMark: CoachMark
        let flatCutoutPathMaker = { (frame: CGRect) -> UIBezierPath in
            return UIBezierPath(rect: frame)
        }
        let coachMarkPointOfInterest = homeCoachMarkViewModel.coachMarkData[index].pointOfInterest
       
        coachMark = coachMarksController.helper.makeCoachMark(
            for: coachMarkPointOfInterest,
            pointOfInterest: coachMarkPointOfInterest.center,
            cutoutPathMaker: flatCutoutPathMaker
        )
        coachMark.arrowOrientation = .top
        coachMark.gapBetweenCoachMarkAndCutoutPath = 10.0
        return coachMark
    }

**Comment by bevanchristian** [comment]
same with me this is my code

```
  func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkAt index: Int) -> CoachMark {
        var coachMark: CoachMark
        let flatCutoutPathMaker = { (frame: CGRect) -> UIBezierPath in
            return UIBezierPath(rect: frame)
        }
        let coachMarkPointOfInterest = homeCoachMarkViewModel.coachMarkData[index].pointOfInterest
        
        coachMark = coachMarksController.helper.makeCoachMark(
            for: coachMarkPointOfInterest,
               pointOfInterest: coachMarkPointOfInterest.center,
               cutoutPathMaker: flatCutoutPathMaker
        )
        coachMark.arrowOrientation = .top
        coachMark.gapBetweenCoachMarkAndCutoutPath = 10.0
        return coachMark
    }
```

**Comment by bevanchristian** [comment]
i found the problem 
```
   func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkViewsAt index: Int, madeFrom coachMark: CoachMark) -> (bodyView: (UIView & CoachMarkBodyView), arrowView: (UIView & CoachMarkArrowView)?) {
        let coachMarkBodyView = CoachMarkCustomBodyView()
        var coachMarkArrowView: CoachMarkArrowDefaultView?

        let coachMarkData = homeCoachMarkViewModel.coachMarkData[index]
        coachMarkBodyView.configureBodyView(coachMarkData: coachMarkData)
        coachMarkBodyView.frame = CGRect(x: 10, y: 10, width: self.view.frame.width * 0.8, height: 132)

        if let arrowOrientation = coachMark.arrowOrientation {
            let view = CoachMarkArrowDefaultView(orientation: arrowOrientation)
            print("masuk arrow")
            coachMarkArrowView = view
        }

        return (bodyView: coachMarkBodyView, arrowView: coachMarkArrowView)
        
    }
```

i have to set y to 10 and arrow will appear

**Comment by ephread** [comment]
Awesome! Closing because a solution was found.
