### ISSUE TITLE
Can the "next" control be at the bottom right corner of each coach mark screen?

### ISSUE THREAD

**Issue by eshwartm** [ephread/Instructions#272]
## Is your feature request related to a problem? Please describe.

Can the "next" control be at the bottom corner of each coach mark screen?

## Describe the solution you'd like

Would want to click next at the bottom right of every coach mark screen.

## Describe alternatives you've considered

alternatives include making a custom view and checking if i can put it along with skip button at the bottom right

**Comment by ephread** [comment]
Hey @eshwartm, the feature was implemented by @ong-yue-huei in #273 (thanks again!)

Usage in [NextPositionViewController.swift#L103](https://github.com/ephread/Instructions/blob/3872fa1a5bc9814217be9c783c6d6a3a53cf6bb0/Examples/Example/Sources/Core/View%20Controllers/Basic%20Examples/NextPositionViewController.swift#L103), let me know if it works for you.
