### ISSUE TITLE
Checking for Objective-C compatibility

### ISSUE THREAD

**Issue by AmanKumarGoswami** [ephread/Instructions#275]
Can we utilize the library with objective C? If yes then can anyone please guide me on the same?

**Comment by ephread** [comment]
Hello @AmanKumarGoswami, it's impossible to use Instructions in Objective-C directly because it uses pure Swift types. It can work with a bit of glue, though. See [previous issues](https://github.com/ephread/Instructions/issues?q=Objective-C) on the topic.
