### ISSUE TITLE
"Stored properties cannot be marked unavailable with '@available' in xcode 15, but working well on previous ver of xcode

### ISSUE THREAD

**Issue by AizatQisti** [ephread/Instructions#307]
![Screenshot 2023-10-10 at 8 42 13 AM](https://github.com/ephread/Instructions/assets/57161145/2bfbd5a3-7384-4e68-86a6-3c45324c9c00)

**Comment by AjayOdedara** [comment]
Same issue here..
<img width="1380" alt="Screenshot 2023-10-21 at 11 22 39" src="https://github.com/ephread/Instructions/assets/29189643/236fd0d0-2a3b-4703-af3b-7ecfbc1ff1bd">

**Comment by AjayOdedara** [comment]
@AizatQisti  I just moved to SPM and the error resolved.

**Comment by ephread** [comment]
Fixed by #295; which is included in version 2.3.0. If you're using CocoaPods, you may need to run `pod repo update` to be able to import 2.3.0.
