### ISSUE TITLE
CochMarkView remains on screen if i touch inside cutout view

### ISSUE THREAD

**Issue by prachil007** [ephread/Instructions#39]
If I press back button inside cutout view, or for matter of fact any button or action. View still remains on screen. Can we add anything that can skip to next coachmarkview.?

For example, If I have small expandable cell with "see more" and I am instructing user to see more but i want next cutout to appear upon clicking on "see more" rather than on ok.

**Comment by prachil007** [comment]
![simulator screen shot 02-may-2016 4 06 23 pm](https://cloud.githubusercontent.com/assets/11495031/14952740/b3bfe916-1080-11e6-9eb8-e11cdbe74821.png)

**Comment by ephread** [comment]
@prachil007: Did you eventually solve your issue?

**Comment by prachil007** [comment]
@ephread Yes. I ended up searching and removing every coachmarkview from self.view after completion of tutorial. There is a delegate method in which I performed that code.


I am facing another issue though

`    private func computeSegmentIndexForLayoutDirection(layoutDirection: UIUserInterfaceLayoutDirection) -> Int {
        let pointOfInterest = coachMark.pointOfInterest!
        var segmentIndex = 3 * pointOfInterest.x / instructionsTopView.bounds.size.width

        if layoutDirection == .RightToLeft {
            segmentIndex = 3 - segmentIndex
        }

        return Int(ceil(segmentIndex))
    }`

In above method, We are getting crash even if we start in viewDidAppear.
Situation when we face crash: In between two coachMarks or click within cutoutview too much rapidly while performing transitions. or By clicking rapidly between coachmerk and cuoutview from which we can transition to other view. Please let me know if you find any solution. I will do same.

**Comment by ephread** [comment]
It's related to to #15. Thanks for providing me with details on how to make the crash happen. ;)

**Comment by prachil007** [comment]
#28 Added Solution. 
@ephread Please recheck the solution. and add it to instruction if you think it is correct one.

**Comment by ephread** [comment]
17a4b40 fixes your initial issue. See #43

As for the second one, when you say:
> transition to other view

Do you mean between controllers or coach marks? The solution you provide in #28 makes me believe you're trying to display coach marks across controllers. If it is the case, Instructions does not support cross controllers walkthrough at the moment.
