### ISSUE TITLE
Prevent tap on custom CustomCoachMarkBodyView and coachMark?

### ISSUE THREAD

**Issue by Foddy** [ephread/Instructions#43]
Hi,

is is possible to prevent the tap events on my coach marks? I just want to show the walkthrough and it shouldn't be possible to tap on the highlighted button for example.

I also wonder why my overlay tap is not working properly. When I tap on the hint text on my custom body view I can't go a step further. I already set up the property "allowOverlayTap" to true and disabled user interaction in my custom body view class on any view. It only works when I tap on an empty area but not if tap on the hint text?

Thank you in advance!

Best

**Comment by A1exandre** [comment]
Same here, I'd like to prevent tap on my coach marks. In my situation I show the user a button during the walkthrough. If the user does not tap on "OK" but on the actual button, another view pops up and messes up the walkthrough.

**Comment by Foddy** [comment]
Hi,

I solved the problem in the meantime by checking on each highlighted button first if the walk through is currently active / visible. If this is the case prevent the action by an empty return before continuing to the button's logic. Additionally you could programmatically go one step further in your walk though with every tap on an highlighted button.

It must be not the best solution because of the additional code and check operation on every highlighted button but it seems to be the only working one for now since there is no official setting to prevent this.

**Comment by A1exandre** [comment]
Thanks! I'll do the same. I bet this will be solved in a more elegant way by ephread's next milestone " Cross controllers walkthrough"

**Comment by ephread** [comment]
@Foddy, @A1exandre: Yeah, d411adc has some side-effects, that's an oversight on my end. I'll fix this as soon as possible!

**Comment by ephread** [comment]
17a4b40 should fix the issue. You can now specify `allowTouchInsideCutoutPath` for a `CoachMark`. The default value is `false`. Sorry for the lack of reactivity.
