### ISSUE TITLE
Cutouts appear in the wrong place when the In Call Status Bar is displayed

### ISSUE THREAD

**Issue by hjo** [ephread/Instructions#44]
Coach marks work well normally but if a call comes in (you can do this in the simulator by toggling the In Call Status Bar) the cutout won't be in the right place anymore. Perhaps the cutout can be shifted when the status bar appears?

![screenshot_22](https://cloud.githubusercontent.com/assets/1050070/15665582/43dab28a-274f-11e6-8a04-a884cd4d4aae.png)

**Comment by ephread** [comment]
Hello @hjo, thanks for reporting the issue! I totally missed the In Call Status Bar, I'll look into it.
