### ISSUE TITLE
Fatal Error: Instructions could not be properly attached to the window, did you call `startOn` inside `viewDidLoad` instead of `ViewDidAppear`

### ISSUE THREAD

**Issue by TThana** [ephread/Instructions#45]
attachToViewController: Instructions could not be properly attached to the window, did you call `startOn` inside `viewDidLoad` instead of `ViewDidAppear`?

The message is shown from 
 private func computeSegmentIndexForLayoutDirection(layoutDirection: UIUserInterfaceLayoutDirection) -> Int {
        let pointOfInterest = coachMark.pointOfInterest!
        var segmentIndex = 3 * pointOfInterest.x / instructionsTopView.bounds.size.width

        if layoutDirection == .RightToLeft {
            segmentIndex = 3 - segmentIndex
        }

        return Int(ceil(segmentIndex))
    }

**Comment by TThana** [comment]
my code

  let coachMarksController = CoachMarksController()

  
  
  required init(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    
    self.view = HomeView(controller: self)
    self.coachMarksController.dataSource = self
    
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    AppDelegate.app().homeViewController = self
    coachMarksController.startOn(self)
     }
  
  override func didReceiveMemoryWarning() {
    super.didReceiveMemoryWarning()
    // Dispose of any resources that can be recreated.
  }
  

  func numberOfCoachMarksForCoachMarksController(coachMarkController: CoachMarksController)
    -> Int {
      return 1
  }
  
  func coachMarksController(coachMarksController: CoachMarksController, coachMarksForIndex: Int)
    -> CoachMark {
      
      let v = self.view as! HomeView
      return coachMarksController.coachMarkForView(v.searchBar){ (frame: CGRect) -> UIBezierPath in
        // This will make a cutoutPath matching the shape of
        // the component (no padding, no rounded corners).
        return UIBezierPath(rect: frame)
      }

  }
  
  func coachMarksController(coachMarksController: CoachMarksController, coachMarkViewsForIndex: Int, coachMark: CoachMark)
    -> (bodyView: CoachMarkBodyView, arrowView: CoachMarkArrowView?) {
      let coachViews = coachMarksController.defaultCoachViewsWithArrow(true, arrowOrientation: coachMark.arrowOrientation)
      
      coachViews.bodyView.hintLabel.text = "Hello! I'm a Coach Mark!"
      coachViews.bodyView.nextLabel.text = "Ok!"
      
      return (bodyView: coachViews.bodyView, arrowView: coachViews.arrowView)
  }

**Comment by galharth** [comment]
+1
Did you solve this problem? Same problem here :/

**Comment by edenfisher** [comment]
+1

**Comment by galharth** [comment]
You need to put the coachMarksController.startOn(self) on viewdidappear

**Comment by ephread** [comment]
@galharth :+1:

Closing. If the issue happens to come from another place, please consolidate #46.
