### ISSUE TITLE
computeSegmentIndexForLayoutDirection: instructionsTopView.bounds.size.width is 0, segmentIndex is +Inf 

### ISSUE THREAD

**Issue by galharth** [ephread/Instructions#46]
`computeSegmentIndexForLayoutDirection: instructionsTopView.bounds.size.width is 0, segmentIndex is +Inf 
`
I'm getting the error:
`attachToViewController: Instructions could not be properly attached to the window, did you call`startOn`inside`viewDidLoad`instead of`ViewDidAppear`?
`
Although I put the startOn on viewdidappear...

**Comment by edenfisher** [comment]
+1

**Comment by galharth** [comment]
If I add an afterDelay of 0 when I run the function it works
`self.performSelector(#selector(BattleViewController.initInstructions), withObject: nil, afterDelay: 0)`

**Comment by ephread** [comment]
Hello @galharth, thanks for reporting the problem. This is a nasty one, few people have been ecountering the issue, but I have neither been able to reproduce the issue, nor track down the problem. It's especially interesting that dispatching the call on the main queue removes the issue. I'll look into it.

**Comment by ephread** [comment]
Closing, as the issue has probably become irrelevant following the numerous refactoring.
