### ISSUE TITLE
Instructions was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by maysamsh** [ephread/Instructions#47]
When I'm implementing ```func coachMarksController(coachMarksController: CoachMarksController, coachMarkWillLoadForIndex index: Int) -> Bool```  I get a runtime error:
**Instructions was compiled with optimization - stepping may behave oddly; variables may not be available.**

the delegate is set to self.

**Comment by ephread** [comment]
Hello @maysamsh, thanks for reporting the issue. Are you using Carthage or CocoaPods to import Instructions in your project?

**Comment by maysamsh** [comment]
I guess it was my fault. I was trying to return false just before starting the show.
