### ISSUE TITLE
Multiple coachmarks when tapping overlayview rapidly.

### ISSUE THREAD

**Issue by iamZoltanVaradi** [ephread/Instructions#48]
First off, great project!
Second: When the user taps the overlayview quickly, `showNextCoachMark` gets called instantly multiple times and one or more coachmarkviews get stuck on the screen. 
I also did a quick fix, feel free to use it if You want to. 
1) Add a second gesture recognizer to the overlayView that detects double taps: (no need for it to have an action)
```
private lazy var doubleTapGestureRecognizer: UITapGestureRecognizer = {
        let gestureRecognizer = UITapGestureRecognizer(target: self, action: "handleDoubleTap:")
        gestureRecognizer.numberOfTapsRequired = 2
        
        return gestureRecognizer
    }()
```
2) Make sure singe tap gesture recognizer only detects tap when double tap fails:
```
private lazy var singleTapGestureRecognizer: UITapGestureRecognizer = {
        let gestureRecognizer = UITapGestureRecognizer(target: self, action: "handleSingleTap:")
        gestureRecognizer.requireGestureRecognizerToFail(self.doubleTapGestureRecognizer)
        
        return gestureRecognizer
    }()
```
3) Add double tap gesture recognizer where the single tap recognizer is added:
```
var allowOverlayTap: Bool {
        get {
            return self.singleTapGestureRecognizer.view != nil
        }

        set {
            if newValue == true {
                self.addGestureRecognizer(self.singleTapGestureRecognizer)
                self.addGestureRecognizer(self.doubleTapGestureRecognizer)
            } else {
                self.removeGestureRecognizer(self.singleTapGestureRecognizer)
            }
        }
    }
```

Bug fixed.

**Comment by ephread** [comment]
Hello @iamZoltanVaradi, good job! Can you make a pull request out of it?

**Comment by ephread** [comment]
[0.4.2](https://github.com/ephread/Instructions/tree/0.4.2) fixes most of the timing-related issues.
