### ISSUE TITLE
Most classes not accessible from Objective-C

### ISSUE THREAD

**Issue by tarekskr** [ephread/Instructions#54]
Most of your classes are not accessible from Objective-C since they don't descend from NSObject. You can fix that by simply preceding their declaration with '@objc'.

Thanks!

**Comment by ephread** [comment]
Hello @tarekskr, the library can't support _mix & match_, since it's using pure swift types. You can neither bridge structs, nor tuples, hence Instructions will never be able to be properly bridged to Objective-C. See #12 for a possible workaround.

**Comment by tarekskr** [comment]
Thanks for your reply.

**Comment by ephread** [comment]
You're welcome!
