### ISSUE TITLE
Bubble color?

### ISSUE THREAD

**Issue by MihaelIsaev** [ephread/Instructions#56]
Hello!

Please tell me how to set the color of the bubble?

```swift
coachViews.bodyView.backgroundColor = UIColor.redColor()
```

The above code is wrong, what is the right solution?

**Comment by MihaelIsaev** [comment]
As a solution I just create custom body and arrow views, but it wasn't simple way..

**Comment by nahouto** [comment]
can you share your code please ?

**Comment by ephread** [comment]
Please see #82. 🙂
