### ISSUE TITLE
Rotating device duplicates marks

### ISSUE THREAD

**Issue by Damnum** [ephread/Instructions#57]
Rotating the device during instructions from portrait to landscape (or the other way round) duplicates the coach marks and messes up the instructions. Reproduced by running the example code.

Maybe the easiest solution is to disable device rotation when instructions are ongoing but I wonder if there is a better solution.

**Comment by ephread** [comment]
Thanks for reporting the issue @Damnum!

That's a bug introduced by the latest release, it used to work fine, I'll fix it as soon as possible.
