### ISSUE TITLE
Changing orientation causes multiple marks or causes mark to not be erased.

### ISSUE THREAD

**Issue by briankeane** [ephread/Instructions#60]
Hello!

Thanks so much for the work on this library -- it really looks great.

My app requires an orientation change mid-tour and it gets a little screwy when changing orientation while a mark is showing.  In my app it causes whatever mark was showing to never disappear.

In the sample app if you go to the 'TransitionFromCode' screen and change orientation while a mark is showing, this is what you get:

<img width="662" alt="screen shot 2016-08-02 at 4 03 03 pm" src="https://cloud.githubusercontent.com/assets/6233176/17345276/d7338640-58ca-11e6-9cc4-98cae965c7f4.png">

Thanks again!

**Comment by ephread** [comment]
Hello @briankeane! Please see #57, a fix is coming soon!

**Comment by briankeane** [comment]
Got it -- sorry about that!  Thanks and nice work!

**Comment by ephread** [comment]
Thanks and no problem!
