### ISSUE TITLE
Add ability to control blur radius of overlay view

### ISSUE THREAD

**Issue by shergin** [ephread/Instructions#64]
Yes, it is not so easy but it is possible with this approach: https://github.com/shergin/Bluuur/blob/master/Bluuur/Classes/MLWLiveBlurView.m

Or, alternativly, add ability to set custom overlay view.

**Comment by ephread** [comment]
Hey @shergin! I don't believe that the ability to provide a custom overlay will ever be implemented, as it's going to be very difficult to satisfy simultaneously all the requirements between the cutoutPath, the touch events forwarding and the customization.

That said, it's certainly possible to implement this feature in the future, using the method you've provided. It might take some time, though, as the features relating to the blurring capabilities of the overlay are considered a low priority at the moment.

**Comment by howiesommerfeld** [comment]
@ephread is it possible to add a shadow to the cutout of the overlay?

**Comment by ephread** [comment]
@howiesommerfeld, not at the moment, unfortunately.

**Comment by ephread** [comment]
Sadly, I'm going to close this issue. It's unlikely this will ever be supported. 😕
