### ISSUE TITLE
Master seems to be missing last swift3 commit 

### ISSUE THREAD

**Issue by artonragsdale** [ephread/Instructions#70]
commit hash: a855515b7a3973a46ac05dbd3df789b3f39190dc

**Comment by ephread** [comment]
Hello @artonragsdale, until the official release of Swift 3, you will have to use the `swift3` branch. `master` will keep supporting 2.3 for the moment. ;)

**Comment by artonragsdale** [comment]
Ah ok, I guess I misread the commit history. Thanks!
