### ISSUE TITLE
Value of type 'CoachMarksController' has no member 'coachMarkForView' (Swift 3)

### ISSUE THREAD

**Issue by OtherF** [ephread/Instructions#71]
Hello,

I tried to add Instructions to my project (Xcode 8, Swift 3) but stuck.

There is no this code:
```
func coachMarksController(coachMarksController: CoachMarksController, coachMarksForIndex: Int) -> CoachMark {
    return coachMarksController.coachMarkForView(self.pointOfInterest)
}
```

But this:
```
func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkAt index: Int) -> CoachMark {
        return coachMarksController.coachMarkForView(self.pointOfInterest)
    }
```
and I receive the error:
```
Value of type 'CoachMarksController' has no member 'coachMarkForView'
```

Could you please help me with the issue?

**Comment by ephread** [comment]
In the swift 3 version (which is still experimental), some methods have been renamed, to fit the new guidelines. I haven't created a migration guide yet, but Xcode should help you finding out the new names.

In that particular case, `CoachMarkController.coachMarkForView(_:pointOfInterest: bezierPathBlock:)` has been renamed to `CoachMarkController.helper.makeCoachMark(for:pointOfInterest:cutoutPathMaker:)`.

I suggest you to take a look at the [Examples/](https://github.com/ephread/Instructions/tree/swift3/Example) (in the `swift3` branch), which use the renamed functions.

**Comment by ephread** [comment]
I think the problem has been solved – closing.
