### ISSUE TITLE
What is the right line in pod file to have Swift3 syntax?

### ISSUE THREAD

**Issue by fprosper** [ephread/Instructions#72]
Right now I have pod 'Instructions', '~> 0.4' but it doesn't seem to be implementing Swift3? Same goes for 0.5, it throws many errors.

**Comment by ephread** [comment]
Hello @fprosper!

```ruby
pod 'Instructions', git: 'https://github.com/ephread/Instructions.git', branch: 'swift3'
```

That's untested, but that's the syntax, as far as I recall.

A version will be published soon.

**Comment by fprosper** [comment]
Thank you!
