### ISSUE TITLE
Coachmarks not showing in containerviews

### ISSUE THREAD

**Issue by hixfield** [ephread/Instructions#75]
I have a viewcontroller that has a containerview in it (via IB). When I add coachmarks to the viewcontroller inside the containerview (embedded) nothing shows up.
Is there a requirement that coachmarks only work for toplevel viewcontrollers?

**Comment by ephread** [comment]
> Is there a requirement that coachmarks only work for toplevel viewcontrollers?

Not willingly. I never considered the possibility of adding coach marks to an embedded view controller, but that's a use-case for which Instructions _should_ work flawlessly. 😉 

Thanks for reporting the issue, I'll look into it.

**Comment by ephread** [comment]
@hixfield: I haven't been able to reproduce the problem, would you be able to provide me with a sample project showing the issue?

The example project has been updated with a simple controller containment scenario, which seem to work. Can you confirm it works for you as well?

**Comment by hixfield** [comment]
confirmed it works now. Just tested it in detail.
