### ISSUE TITLE
Is it possible enable touch only for Cutout view, instead of all background?

### ISSUE THREAD

**Issue by avshiyanov** [ephread/Instructions#78]

**Comment by ephread** [comment]
It depends on what you mean exactly. You can enable touch on the coach mark, on the overlay, and also on both of them at the same time. Additionally, you can also forward the touch event to the view sitting under the cutout path.

But there is no touch detection on the cutout path itself.

**Comment by yahmad** [comment]
@ephread I am trying to pass through events to views under the overlay - basically, don't want to block any user events. I noticed there seems to be code that allows passing events through (PassthroughView?), but can't see a flag or setting to tell it to do this. 

Could you explain the best way to have the overlay pass all events through, similar to how `allowTouchInsideCutoutPath` works with the cutout?
