### ISSUE TITLE
didFinishShowingAndWasSkipped is called even when curCoachmark was not started

### ISSUE THREAD

**Issue by edenfisher** [ephread/Instructions#79]
I'm using 'didFinishShowingAndWasSkipped' delegate method to determine what happens after the user sees the coachMark. The problem is that the method is getting called even if I did not called startOn on the coachMark.
Any ideas why?
Thank you

**Comment by galharth** [comment]
+1

**Comment by ephread** [comment]
Hey @edenfisher, thanks for reporting the issue. Which version are you using ?

**Comment by edenfisher** [comment]
0.5.0

**Comment by ephread** [comment]
Thanks, I'll investigate. ;)

**Comment by ephread** [comment]
I've never been able to reproduce the issue, I'm closing it for now. Feel free to reopen.
