### ISSUE TITLE
Keep the TitleView showing above the overlay

### ISSUE THREAD

**Issue by eliekarouz** [ephread/Instructions#84]
I want to keep the tiltleView of the UINavigationItem above the overlay. 
Is there an easy way to do it?

**Comment by ephread** [comment]
Hey @eliekarouz, sadly it's not really possible at the moment. The feature may be implemented in the future, though.

**Comment by eliekarouz** [comment]
Hey @ephread, 

I am bringing this up again because we really need it. Two years ago, I forked the repo last time and did some changes but they weren't that clean (at least to put it back in the main repo). What I actually did is took a snapshot of the title view and add it to the overlay view at the same position of the main title view. I had to hide the title view of the main screen because the its borders looked thicker when adding the title view of the overlay above the real title view. 

I would like to submit a pull request for this but I would like to hear any feedback from you on how you think the API should be... I am still confused if it's better to pass the real titleView to the CoachMarkController and we take a snapshot of it and add it to the overlay view OR let the user be in control so he creates a new titleView and passes it the CoachMarkController along with the the position where we are going to add it.

**Comment by ephread** [comment]
@eliekarouz I believe you can achieve something similar as of 1.2.2, just use the [`viewController`](https://github.com/ephread/Instructions#presentation-context) presentation context and Instructions should be added to `UIViewController.view`. Be careful to not change the existing hierarchy too much while the coach marks are displayed though.

**Comment by eliekarouz** [comment]
But I think that the whole navigation bar including the bar items will not be covered by the overlay.
