### ISSUE TITLE
Is it possible to add an instruction to a UIBarButtonItem?

### ISSUE THREAD

**Issue by rimckenn** [ephread/Instructions#87]
UIBarButtonItem doesn't inherit from UIView, so was wondering if it is possible to set a coach marker originating from a UIBarButtonItem in the navigation bar? Thanks.

**Comment by rimckenn** [comment]
Ok, I see from another example, that you can get the UIView from code like

`leftBarButton.valueForKey("view") as! UIView`

Thanks.

**Comment by phatmann** [comment]
This may work, but it uses an undocumented property and Is thus risky. Would be better to have direct support for bar button items.

**Comment by ephread** [comment]
@phatmann: I don't know of any other way to get the frame of an `UIBarButtonItem`, thus, if Instructions bundled a helper providing the feature, it would use the KVC method internally. As you perfectly stated, it's risky, that's why I prefer letting my fellow developer explicitly request the view. :wink:

**Comment by hamidptb** [comment]
I find a tricky way to do this and I'm currently using it in my app :

1- get status bar height:
`var statusBarHeight: CGFloat = 0
            if #available(iOS 13.0, *) {
                statusBarHeight = UIApplication.shared.keyWindow?.windowScene?.statusBarManager?.statusBarFrame.height ?? 0
            } else {
                statusBarHeight = UIApplication.shared.statusBarFrame.height
            }`

2- make a custom uiview to simulate uibarbuttonitem size:
`let barItemView = UIView()
            barItemView.frame = CGRect(x: 5, y: statusBarHeight, width: 50, height: 50)
            self.view.addSubview(barItemView)`

3- using from this view as requested uiview in func:
`return coachMarksController.helper.makeCoachMark(for: barItemView)`
