### ISSUE TITLE
Tap on the pointed view

### ISSUE THREAD

**Issue by buscarini** [ephread/Instructions#96]
I would like to make the user tap on the pointed buttons. I think this would be better, as the user would be doing the action and seeing the results instead of reading (and maybe forgetting) what they do. Is there a way to do this? I've looked at the api, but I haven't found anything.

**Comment by ephread** [comment]
Hey @buscarini, the property [`allowTouchInsideCutoutPath `](https://github.com/ephread/Instructions#customizing-how-the-coach-mark-will-show) might be what you're looking for. ;)

**Comment by buscarini** [comment]
Great, thanks! from the explanation I didn't get that it was meant for this
