### ISSUE TITLE
Umbrella header for module 'Instructions' does not include header 'Instructions-AppExtensions-umbrella.h'

### ISSUE THREAD

**Issue by evgeniyd** [ephread/Instructions#97]
Instructions is imported via CocoaPods **v1.0.1**

The `Podfile`:

    platform :ios, '9.0'
    
    project 'MyProject.xcodeproj'
    
    use_frameworks!
    inhibit_all_warnings!
    
    target 'Application' do
        use_frameworks!
        # ...
        pod 'Instructions', :git => 'https://github.com/ephread/Instructions.git', :branch => 'master'
        # ...
    end
    
    target 'Extension' do
        use_frameworks!
        # ...
        pod 'Instructions/AppExtensions', :git => 'https://github.com/ephread/Instructions.git', :branch => 'master'
        # ...
    end

`Podfile.lock`shows this locked versions:

    - Instructions (0.5.0):
      - Instructions/Core (= 0.5.0)
    - Instructions/AppExtensions (0.5.0)
    - Instructions/Core (0.5.0)

During the Achieve, Xcode 8.2.1 shows this warning:

    /Users/admin/Developer/repo/my-project-ios/Pods/<module-includes>:1:1: Umbrella header for module 'Instructions' does not include header 'Instructions-AppExtensions-umbrella.h'

**Comment by ephread** [comment]
Hey @evgeniyd, CocoaPods changed its internal a couple of months ago, which means the subspec-based app extension flavor doesn't work anymore. As far as know, there aren't any workaround, I'm going to have to separate the subspecs into two specs.

**Comment by evgeniyd** [comment]
@ephread thank you very much for your response

I edited the `Podfile`'s Instructions record while migrating from CocoaPods v1.0.1 to v1.1.0.

My project uses Instructions for iOS extension **only**. The iOS keyboard appex, in particular.

Now, `Podfile` looks like this:

    target 'Application' do
    # ...
    end
    
    target 'Keyboard' do
    # ...
    pod 'Instructions/AppExtensions', :git => 'https://github.com/ephread/Instructions.git', :branch => 'master' # Swift 3 support
    # ...
    end

...notice, there is no Instructions imported into main app. It works as far as I can tell.

About the warning, I'll update the comment during next archiving. I believe it is still there. 

Also, [Mixpanl](https://github.com/mixpanel/mixpanel-iphone) did separate podspecs for app and appex.

**Comment by ephread** [comment]
Great, I assumed you needed to use both flavors. Glad to hear you've been able to make it work!

**Comment by ephread** [comment]
It's now fixed, with the release of [`InstructionsAppExtensions`](https://cocoapods.org/pods/InstructionsAppExtensions) as a seperate pod.
